---
title: "Untitled"
output:
  pdf_document: default
  html_document: default
date: "2024-06-07"
---

```{r}
knitr ::opts_chunk$set(echo= TRUE)
```

```{r}

library(readr)

# Read the CSV file
# Install readr package if not already installed
install.packages("readr")

# Load the readr library
library(readr)

# Read the CSV file with UTF-8 encoding
SouthKorea_Road <- read_csv("SouthKorea_road.csv", locale = locale(encoding = "EUC-KR"))
Garosu_Gil <- read_csv("Garosu_Gil.csv", locale = locale(encoding = "EUC-KR"))
Traditional_heritage<- read_csv("Traditional_heritage.csv", locale = locale(encoding = "EUC-KR"))
Cultural_Festival<- read_csv("Cultural Festival.csv", locale = locale(encoding = "EUC-KR"))
Specific_Road<- read_csv("Specific_Road.csv", locale = locale(encoding = "EUC-KR"))
Accommodation <- read_csv("Accommodation.csv", locale = locale(encoding = "EUC-KR"))
Waterpark <- read_csv("Waterpark.csv", locale = locale(encoding = "EUC-KR"))
Museum<- read_csv("Museum.csv", locale = locale(encoding = "EUC-KR"))
Recreational_forest <-read_csv("Recreational_forest.csv", locale = locale(encoding = "EUC-KR"))
Performance <- read_csv("Performance.csv", locale = locale(encoding = "EUC-KR"))
exp_vis_search <- read_csv("exp+vis+search.csv", locale = locale(encoding = "EUC-KR")) 

head(SouthKorea_Road)
head(Garosu_Gil)
head(Traditional_heritage)
head(Cultural_Festival)
head(Specific_Road)
head(Accommodation)
head(Waterpark)
head(Museum)
head(Recreational_forest)
head(Performance)
head(P_N_Tourists)
head(exp_vis_search)

View(SouthKorea_Road)
View(Garosu_Gil)
View(Traditional_heritage)
View(Cultural_Festival)
View(Specific_Road)
View(Accommodation)
View(Waterpark)
View(Museum)
View(Recreational_forest)
View(Performance)
View(P_N_Tourists)
head(exp_vis_search)

colnames(Recreational_forest)
```


```{r}
colnames(SouthKorea_Road) <- c("Road Name", "Road Description", "Total Length", "Total Travel Time", 
                   "Start Point Name", "Start Point Address", "Start Point Sub-Address (optional)", 
                   "End Point Name", "End Point Address", "End Point Sub-Address (optional)", 
                   "Route Information", "Administrative Agency Phone Number", "Administrative Agency Name", 
                   "Data Reference Date", "Providing Agency Code", "Providing Agency Name") 
colnames(Garosu_Gil) <- c("Street Tree Road Name", "Street Tree Road Start Latitude", "Street Tree Road Start Longitude", 
                   "Street Tree Road End Latitude", "Street Tree Road End Longitude", "Tree Species", 
                   "Number of Street Trees", "Street Tree Road Length", "Planting Year", "Street Tree Road Description", 
                   "Road Name", "Road Type", "Road Section", "Administrative Agency Phone Number", "Administrative Agency Name", 
                   "Data Reference Date", "Providing Agency Code", "Providing Agency Name")

```


```{r}
colnames(Traditional_heritage) <- c("Cultural Heritage Name", 
                                   "Cultural Heritage Designation Number", 
                                   "Cultural Heritage Type", 
                                   "Cultural Heritage Category", 
                                   "Road Address", 
                                   "Lot/Block Address", 
                                   "Latitude", 
                                   "Longitude", 
                                   "Designation Date", 
                                   "Ownership Type", 
                                   "Owner Name", 
                                   "Size",
                                   "Creation Era", 
                                   "Image Information",  
                                   "Cultural Heritage Introduction",  
                                   "Management Institution Phone Number", 
                                   "Management Institution Name", 
                                   "Data Reference Date",  
                                   "Provider Institution Code",
                                   "Provider Institution Name") 

colnames(Cultural_Festival) <- c(
  "Festival Name",
  "Venue",
  "Festival Start Date",
  "Festival End Date",
  "Festival Description",
  "Organizing Institution Name",
  "Hosting Institution Name",
  "Sponsoring Institution Name",
  "Phone Number",
  "Website Address",
  "Additional Information",
  "Road Address",
  "Lot/Block Address",
  "Latitude",
  "Longitude",
  "Data Reference Date",
  "Provider Institution Code",
  "Provider Institution Name"
)

colnames(Specific_Road) <- c(
  "Special Road Name",
  "Road Description",
  "Road Address",
  "Lot/Block Address",
  "Latitude",
  "Longitude",
  "Total Length",
  "Number of Stores",
  "Designation Year",
  "Management Institution Phone Number",
  "Management Institution Name",
  "Data Reference Date",
  "Provider Institution Code",
  "Provider Institution Name"
)

colnames(Accommodation) <- c(
  "ID",
  "Open Service Name",
  "Open Service ID",
  "Open Local Government Code",
  "Management Number",
  "License Issuance Date",
  "License Cancellation Date",
  "Business Status Code",
  "Business Status Name",
  "Detailed Business Status Code",
  "Detailed Business Status Name",
  "Closure Date",
  "Business Start Date",
  "Business End Date",
  "Reopening Date",
  "Facility Phone Number",
  "Facility Area",
  "Facility Zip Code",
  "Full Facility Address",
  "Full Road Address",
  "Road Zip Code",
  "Facility Name",
  "Last Updated",
  "Data Update Type",
  "Data Update Date",
  "Business Type Name",
  "X Coordinate",
  "Y Coordinate",
  "Cultural Sports Industry Name",
  "Cultural Business Type Name",
  "Region Name",
  "Total Floors",
  "Surrounding Environment Name",
  "Products and Services",
  "Insurance Company Name",
  "Building Use Name",
  "Number of Ground Floors",
  "Number of Basement Floors",
  "Number of Rooms",
  "Building Floor Area",
  "English Facility Name",
  "English Facility Address",
  "Ship Gross Tonnage",
  "Number of Ships",
  "Ship Specifications",
  "Stage Area",
  "Number of Seats",
  "Souvenir Types",
  "Meeting Room Capacity",
  "Facility Area",
  "Amusement Ride Details",
  "Number of Amusement Rides",
  "Broadcasting Facility",
  "Power Facility",
  "Medical Room",
  "Information Center",
  "Travel Insurance Start Date",
  "Travel Insurance End Date",
  "Capital",
  "Insurance Start Date",
  "Insurance End Date",
  "Ancillary Facilities",
  "Facility Size"
)

colnames(Waterpark) <- c(
  "ID",
  "Open Service Name",
  "Open Service ID",
  "Open Local Government Code",
  "Management Number",
  "License Issuance Date",
  "License Cancellation Date",
  "Business Status Code",
  "Business Status Name",
  "Detailed Business Status Code",
  "Detailed Business Status Name",
  "Closure Date",
  "Business Start Date",
  "Business End Date",
  "Reopening Date",
  "Facility Phone Number",
  "Facility Area",
  "Facility Zip Code",
  "Full Facility Address",
  "Full Road Address",
  "Road Zip Code",
  "Facility Name",
  "Last Updated",
  "Data Update Type",
  "Data Update Date",
  "Business Type Name",
  "X Coordinate",
  "Y Coordinate",
  "Cultural Sports Industry Name",
  "Cultural Business Type Name",
  "Region Name",
  "Total Floors",
  "Surrounding Environment Name",
  "Products and Services",
  "Insurance Company Name",
  "Building Use Name",
  "Number of Ground Floors",
  "Number of Basement Floors",
  "Number of Rooms",
  "Building Floor Area",
  "English Facility Name",
  "English Facility Address",
  "Ship Gross Tonnage",
  "Number of Ships",
  "Ship Specifications",
  "Stage Area",
  "Number of Seats",
  "Souvenir Types",
  "Meeting Room Capacity",
  "Facility Area",
  "Amusement Ride Details",
  "Number of Amusement Rides",
  "Broadcasting Facility",
  "Power Facility",
  "Medical Room",
  "Information Center",
  "Travel Insurance Start Date",
  "Travel Insurance End Date",
  "Capital",
  "Insurance Start Date",
  "Insurance End Date",
  "Ancillary Facilities",
  "Facility Size"
)

colnames(Museum) <- c(
  "Facility Name",
  "Museum/Art Gallery Type",
  "Road Address",
  "Lot/Block Address",
  "Latitude",
  "Longitude",
  "Operating Institution Phone Number",
  "Operating Institution Name",
  "Operating Website",
  "Amenities Information",
  "Weekdays Opening Start Time",
  "Weekdays Opening End Time",
  "Public Holidays Opening Start Time",
  "Public Holidays Opening End Time",
  "Closure Information",
  "Adult Admission Fee",
  "Teen Admission Fee",
  "Child Admission Fee",
  "Admission Fee Other Information",
  "Museum/Art Gallery Introduction",
  "Transportation Information",
  "Management Institution Phone Number",
  "Management Institution Name",
  "Data Reference Date",
  "Provider Institution Code",
  "Provider Institution Name"
)

colnames(Performance) <- c(
  "Event Name",
  "Venue",
  "Event Description",
  "Event Start Date",
  "Event End Date",
  "Event Start Time",
  "Event End Time",
  "Ticket Information",
  "Organizing Institution Name",
  "Hosting Institution Name",
  "Phone Number",
  "Sponsoring Institution Name",
  "Number of Seats",
  "Ticket Price",
  "Age Restriction",
  "Discount Information",
  "Important Notes",
  "Website Address",
  "Booking Information",
  "Parking Availability",
  "Road Address",
  "Lot/Block Address",
  "Latitude",
  "Longitude",
  "Data Reference Date",
  "Provider Institution Code",
  "Provider Institution Name"
)

colnames(Recreational_forest) <- c(
  "Recreation Forest Name" = "ID",
  "Province Name",
  "Recreation Forest Type",
  "Recreation Forest Area",
  "Capacity",
  "Entrance Fee",
  "Accommodation Availability",
  "Main Facilities",
  "Street Address",
  "Managing Agency",
  "Recreation Forest Phone Number",
  "Website",
  "Latitude",
  "Longitude",
  "Data Reference Date",
  "Provider Code",
  "Provider Name"
) 

```


```{r}
head(SouthKorea_Road)
head(Garosu_Gil)
head(Traditional_heritage)
head(Cultural_Festival)
head(Specific_Road)
head(Accommodation)
head(Waterpark)
head(Museum)
head(Recreational_forest)       
head(Performance)
head(P_N_Tourists)
```

```{r}
#(1) 
f_SouthKorea_Road <- SouthKorea_Road[, !(names(SouthKorea_Road) %in% c(
  "Administrative Agency Phone Number",
  "Administrative Agency Name",
  "Data Reference Date",
  "Providing Agency Code",
  "Start Point Name",
  "Start Point Address",
  "Start Point Sub-Address (optional)",
  "End Point Name",
  "End Point Address",
  "End Point Sub-Address (optional)"
))]

f_SouthKorea_Road <- f_SouthKorea_Road %>%
  filter(
    rowSums(!is.na(.)) > 0
  ) ;f_SouthKorea_Road

#(2)
f_Garosu_Gil <- Garosu_Gil[, !(names(Garosu_Gil) %in% c(
  "Tree Species",
  "Street Tree Road Start Latitude",
  "Street Tree Road Start Longitude",
  "Street Tree Road End Latitude",
  "Street Tree Road End Longitude",
  "Planting Year",
  "Road Name",
  "Road Type",
  "Road Section",
  "Administrative Agency Phone Number",
  "Administrative Agency Name",
  "Data Reference Date",
  "Providing Agency Code"
))]


f_Garosu_Gil <- f_Garosu_Gil %>%
  filter(
    rowSums(!is.na(.)) > 0
  );f_Garosu_Gil

#(3)
f_Traditional_heritage <- Traditional_heritage[, !(names(Traditional_heritage) %in% c(
  "Cultural Heritage Designation Number",
  "Road Address",
  "Lot/Block Address",
  "Latitude",
  "Longitude",
  "Designation Date",
  "Owner Name",
  "Creation Era",
  "Image Information",
  "Management Institution Phone Number",
  "Data Reference Date",
  "Provider Institution Code",
  "Management Institution Name"
))]


f_Traditional_heritage  <- f_Traditional_heritage  %>%
  filter(
    rowSums(!is.na(.)) > 0
  ) ;f_Traditional_heritage
    
#(4)
f_Cultural_Festival <- Cultural_Festival[, !(names(Cultural_Festival) %in% c(
  "Venue",
  "Hosting Institution Name",
  "Sponsoring Institution Name",
  "Phone Number",
  "Website Address",
  "Additional Information",
  "Latitude",
  "Longitude",
  "Data Reference Date",
  "Provider Institution Code"
))] 

f_Cultural_Festival  <- f_Cultural_Festival  %>%
  filter(
    rowSums(!is.na(.)) > 0
) ;f_Cultural_Festival


#(5)
f_Specific_Road <- Specific_Road[, !(names(Specific_Road) %in% c(
  "Road Address",
  "Lot/Block Address",
  "Latitude",
  "Longitude",
  "Designation Year",
  "Management Institution Phone Number",
  "Management Institution Name",
  "Data Reference Date",
  "Provider Institution Code"
))]

f_Specific_Road  <- f_Specific_Road  %>%
  filter(
    rowSums(!is.na(.)) > 0
) ;f_Specific_Road 

#(6)
f_Accommodation <- Accommodation %>%
  select(c(`Business Status Name`, `Facility Name`, `Facility Size`, `Full Road Address`)) %>%
  filter(!is.na(`Business Status Name`) & !is.na(`Facility Name`) & !is.na(`Facility Size`) & !is.na(`Full Road Address`)) %>%
  filter(`Business Status Name` == "영업/정상") ;f_Accommodation


#(7)
f_Waterpark <- Waterpark %>%
  select(c(`Business Status Name`, `Facility Name`, `Facility Size`, `Full Road Address`)) %>%
  filter(!is.na(`Business Status Name`) & !is.na(`Facility Name`) & !is.na(`Facility Size`) & !is.na(`Full Road Address`)) %>%
  filter(`Business Status Name` == "영업/정상") ;f_Waterpark


#(8)
f_Museum <- Museum %>%
  select(c(`Facility Name`, `Museum/Art Gallery Type`, `Road Address`, 'Amenities Information', 'Admission Fee Other Information','Museum/Art Gallery Introduction','Provider Institution Name' )) %>%
  filter(!is.na(`Facility Name`) & 
         !is.na(`Museum/Art Gallery Type`) & 
         !is.na(`Road Address`) &  
         !is.na('Amenities Information') & 
         !is.na('Admission Fee Other Information') & 
         !is.na('Museum/Art Gallery Introduction') & 
         !is.na('Provider Institution Name')) ;f_Museum


#(9)

# Define the columns to remove
columns_to_remove <- c(
  "Recreation Forest Phone Number",
  "Website",
  "Latitude",
  "Longitude",
  "Data Reference Date",
  "Provider Code"
)

# Remove specific columns from the Recreational_forest data frame
f_Recreational_forest <- Recreational_forest[, !(names(Recreational_forest) %in% columns_to_remove)]

# Filter out rows that have no non-NA values
f_Recreational_forest <- f_Recreational_forest %>%
  filter(rowSums(!is.na(.)) > 0) ; f_Recreational_forest 

 #(10)
 
f_Performance <- Performance %>% select(c(`Event Name`, `Event Description`, `Event Start Date`, `Event End Date` , 'Ticket Information', 'Parking Availability', 'Road Address', 'Provider Institution Name')) %>%
  filter(!is.na(`Event Name`) & 
         !is.na(`Event Description`) & 
         !is.na(`Event Start Date`) & 
         !is.na(`Event End Date`) & 
         !is.na('Ticket Information') & 
         !is.na('Parking Availability') & 
         !is.na('Road Address') & 
         !is.na('Provider Institution Name')) ;f_Performance


```




```{r}
#Make the location column using mutate()

library(dplyr)

# Define the classify_location function
classify_location <- function(address) {
  if (is.na(address)) {
    return(NA)
  } else if (grepl("서울", address)) {
    return("서울특별시")
  } else if (grepl("경기", address)) {
    return("경기도")
  } else if (grepl("충청남도", address) || grepl("충남", address)) {
    return("충청남도")
  } else if (grepl("충청북도", address) || grepl("충북", address)) {
    return("충청북도")
  } else if (grepl("세종", address)) {
    return("세종특별자치시")
  } else if (grepl("대전", address)) {
    return("대전광역시")
  } else if (grepl("전라북도", address) || grepl("전북", address)) {
    return("전라북도")
  } else if (grepl("광주", address)) {
    return("광주광역시")
  } else if (grepl("전라남도", address) || grepl("전남", address)) {
    return("전라남도")
  } else if (grepl("경상북도", address) || grepl("경북", address)) {
    return("경상북도")
  } else if (grepl("\\b대구\\b", address) || grepl("대구광역시", address)) {
    return("대구광역시")
  } else if (grepl("울산", address)) {
    return("울산광역시")
  } else if (grepl("부산", address)) {
    return("부산광역시")
  } else if (grepl("경상남도", address) || grepl("경남", address)) {
    return("경상남도")
  } else if (grepl("제주", address)) {
    return("제주특별자치도")
  } else if (grepl("인천", address)) {
    return("인천광역시")
  } else if (grepl("강원", address)){
    return("강원도")
  } else {
    return(NA)
  }
}

# Mutate the "Region" Column by the criteria above
f_SouthKorea_Road <- f_SouthKorea_Road %>%
  mutate(Region = sapply(`Providing Agency Name`, classify_location))

f_Garosu_Gil <- f_Garosu_Gil %>%
  mutate(Region = sapply(`Providing Agency Name`, classify_location))

f_Traditional_heritage <- f_Traditional_heritage %>%
  mutate(Region = sapply(`Provider Institution Name`, classify_location))

f_Cultural_Festival <- f_Cultural_Festival %>%
  mutate(Region = sapply(`Provider Institution Name`, classify_location))

f_Specific_Road <- f_Specific_Road %>%
  mutate(Region = sapply(`Provider Institution Name`, classify_location))

f_Accommodation <- f_Accommodation %>%
  mutate(Region = sapply(`Full Road Address`, classify_location))

f_Waterpark <- f_Waterpark %>%
  mutate(Region = sapply(`Full Road Address`, classify_location))

f_Museum <- f_Museum %>%
  mutate(Region = sapply(`Road Address`, classify_location))

f_Recreational_forest <- f_Recreational_forest %>%
  mutate(Region = sapply(`Street Address`, classify_location))

f_Performance <- f_Performance %>%
  mutate(Region = sapply(`Road Address`, classify_location))
```




```{r}
# Calculate the number of NA values in the 'Region' column for each cleaned dataset
sum(is.na(f_SouthKorea_Road$Region))
sum(is.na(f_Garosu_Gil$Region))
sum(is.na(f_Traditional_heritage$Region))
sum(is.na(f_Cultural_Festival$Region))
sum(is.na(f_Specific_Road$Region))
sum(is.na(f_Accommodation$Region))
sum(is.na(f_Waterpark$Region))
sum(is.na(f_Museum$Region))
sum(is.na(f_Recreational_forest$Region))
sum(is.na(f_Performance$Region))

# Filter out rows with NA in the 'Region' column for each remaining dataset
f_Specific_Road <- f_Specific_Road %>%
  filter(!is.na(Region))

f_Cultural_Festival <- f_Cultural_Festival %>%
  filter(!is.na(Region))

f_Accommodation <- f_Accommodation %>%
  filter(!is.na(Region))

f_Waterpark <- f_Waterpark %>%
  filter(!is.na(Region))

f_Museum <- f_Museum %>%
  filter(!is.na(Region))

f_Recreational_forest <- f_Recreational_forest %>%
  filter(!is.na(Region))

f_Performance <- f_Performance %>%
  filter(!is.na(Region)) 

#Calculate again after drop NA
sum(is.na(f_SouthKorea_Road$Region))
sum(is.na(f_Garosu_Gil$Region))
sum(is.na(f_Traditional_heritage$Region))
sum(is.na(f_Cultural_Festival$Region))
sum(is.na(f_Specific_Road$Region))
sum(is.na(f_Accommodation$Region))
sum(is.na(f_Waterpark$Region))
sum(is.na(f_Museum$Region))
sum(is.na(f_Recreational_forest$Region))
sum(is.na(f_Performance$Region))

#head of all datasets
head(f_SouthKorea_Road)
head(f_Garosu_Gil)
head(f_Traditional_heritage)
head(f_Cultural_Festival)
head(f_Specific_Road)
head(f_Accommodation)
head(f_Waterpark)
head(f_Museum)
head(f_Recreational_forest)
head(f_Performance)

```



```{r}
#Counting Region and Joining

#(1) Counting Region
SouthKorea_Road_Counts <- f_SouthKorea_Road %>%
  group_by(Region) %>%
  summarise(SouthKorea_Road_Counts = n())

Garosu_Gil_Counts <- f_Garosu_Gil %>%
  group_by(Region) %>%
  summarise(Garosu_Gil_Counts = n())

Traditional_heritage_Counts <- f_Traditional_heritage %>%
  group_by(Region) %>%
  summarise(Traditional_heritage_Counts = n())

Cultural_Festival_Counts <- f_Cultural_Festival %>%
  group_by(Region) %>%
  summarise(Cultural_Festival_Counts = n())

Specific_Road_Counts <- f_Specific_Road %>%
  group_by(Region) %>%
  summarise(Specific_Road_Counts = n())

Accommodation_Counts <- f_Accommodation %>%
  group_by(Region) %>%
  summarise(Accommodation_Counts = n())

Waterpark_Counts <- f_Waterpark %>%
  group_by(Region) %>%
  summarise(Waterpark_Counts = n())

Museum_Counts <- f_Museum %>%
  group_by(Region) %>%
  summarise(Museum_Counts = n())

Recreational_forest_Counts <- f_Recreational_forest %>%
  group_by(Region) %>%
  summarise(Recreational_forest_Counts = n())

Performance_Counts <- f_Performance %>%
  group_by(Region) %>%
  summarise(Performance_Counts = n())

#(2) Joining
Region_Counts <- SouthKorea_Road_Counts %>%
  full_join(Garosu_Gil_Counts, by = "Region") %>%
  full_join(Traditional_heritage_Counts, by = "Region") %>%
  full_join(Cultural_Festival_Counts, by = "Region") %>%
  full_join(Specific_Road_Counts, by = "Region") %>%
  full_join(Accommodation_Counts, by = "Region") %>%
  full_join(Waterpark_Counts, by = "Region") %>%
  full_join(Museum_Counts, by = "Region") %>%
  full_join(Recreational_forest_Counts, by = "Region") %>%
  full_join(Performance_Counts, by = "Region")

Region_Counts <- Region_Counts %>%
  filter(rowSums(!is.na(.)) > 0)


#(3) Region_Counts Visualization

library(ggplot2)

#(3)-1 SouthKorea_Road_Counts Visualization 

Region_Counts <- Region_Counts %>%
  mutate(SouthKorea_Road_Percent = SouthKorea_Road_Counts / sum(SouthKorea_Road_Counts) * 100) %>%
  arrange(desc(SouthKorea_Road_Counts))

ggplot(Region_Counts, aes(x = SouthKorea_Road_Counts, y = reorder(Region, SouthKorea_Road_Counts), fill = Region)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = sprintf("%d (%.1f%%)", SouthKorea_Road_Counts, SouthKorea_Road_Percent)), 
            position = position_dodge(width = 1), hjust = -0.2, size = 3) +
  theme_minimal() +
  labs(title = "지역별 걷기여행길 현황", x = "걷기여행길길 개수", y = "지역") +
   coord_cartesian(xlim = c(0, max(Region_Counts$SouthKorea_Road_Counts) * 1.3)) + 
  theme(legend.position = "right", 
        plot.margin = margin(t = 1, r = 1, b = 1, l = 1, unit = "cm"),
        legend.box.margin = margin(10, 10, 10, 20),
        legend.text = element_text(size = 8),
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 8))


#(3)-2 Garosu_Gil_Counts Visualization 

library(tidyr)

Region_Counts <- Region_Counts %>%
  mutate(Garosu_Gil_Counts = replace_na(Garosu_Gil_Counts, 0)) %>%
  mutate(Garosu_Gil_Percent = Garosu_Gil_Counts / sum(Garosu_Gil_Counts) * 100) %>%
  arrange(desc(Garosu_Gil_Counts))

ggplot(Region_Counts, aes(x = Garosu_Gil_Counts, y = reorder(Region, Garosu_Gil_Counts), fill = Region)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = sprintf("%d (%.1f%%)", Garosu_Gil_Counts, Garosu_Gil_Percent)), 
            position = position_dodge(width = 1), hjust = -0.2, size = 3) +
  theme_minimal() +
  labs(title = "지역별 가로수길 현황", x = "가로수길 개수", y = "지역") +
   coord_cartesian(xlim = c(0, max(Region_Counts$Garosu_Gil_Counts) * 1.3)) + 
  theme(legend.position = "right", 
        plot.margin = margin(t = 1, r = 1, b = 1, l = 1, unit = "cm"),
        legend.box.margin = margin(10, 10, 10, 20),
        legend.text = element_text(size = 8),
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 8))

#(3)-3 Traditional_heritage_Counts Visualization 

Region_Counts <- Region_Counts %>%
  mutate(Traditional_heritage_Counts = replace_na(Traditional_heritage_Counts, 0)) %>%
  mutate(Traditional_heritage_Percent = Traditional_heritage_Counts / sum(Traditional_heritage_Counts) * 100) %>%
  arrange(desc(Traditional_heritage_Counts))

ggplot(Region_Counts, aes(x = Traditional_heritage_Counts, y = reorder(Region, Traditional_heritage_Counts), fill = Region)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = sprintf("%d (%.1f%%)", Traditional_heritage_Counts, Traditional_heritage_Percent)), 
            position = position_dodge(width = 1), hjust = -0.2, size = 3) +
  theme_minimal() +
  labs(title = "지역별 문화유적 현황", x = "문화유적 개수", y = "지역") +
   coord_cartesian(xlim = c(0, max(Region_Counts$Traditional_heritage_Counts) * 1.3)) + 
  theme(legend.position = "right", 
        plot.margin = margin(t = 1, r = 1, b = 1, l = 1, unit = "cm"),
        legend.box.margin = margin(10, 10, 10, 20),
        legend.text = element_text(size = 8),
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 8))

#(3)-4 Cultural_Festival_Counts Visualization 

Region_Counts <- Region_Counts %>%
  mutate(Cultural_Festival_Counts = replace_na(Cultural_Festival_Counts, 0)) %>%
  mutate(Cultural_Festival_Percent = Cultural_Festival_Counts / sum(Cultural_Festival_Counts) * 100) %>%
  arrange(desc(Cultural_Festival_Counts))

ggplot(Region_Counts, aes(x = Cultural_Festival_Counts, y = reorder(Region, Cultural_Festival_Counts), fill = Region)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = sprintf("%d (%.1f%%)", Cultural_Festival_Counts, Cultural_Festival_Percent)), 
            position = position_dodge(width = 1), hjust = -0.2, size = 3) +
  theme_minimal() +
  labs(title = "지역별 문화축제 현황", x = "문화축제수", y = "지역") +
   coord_cartesian(xlim = c(0, max(Region_Counts$Cultural_Festival_Counts) * 1.3)) + 
  theme(legend.position = "right", 
        plot.margin = margin(t = 1, r = 1, b = 1, l = 1, unit = "cm"),
        legend.box.margin = margin(10, 10, 10, 20),
        legend.text = element_text(size = 8),
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 8))

#(3)-5 Specific_Road_Counts Visualization 

Region_Counts <- Region_Counts %>%
  mutate(Specific_Road_Counts = replace_na(Specific_Road_Counts, 0)) %>%
  mutate(Specific_Road_Counts_Percent = Specific_Road_Counts / sum(Specific_Road_Counts) * 100) %>%
  arrange(desc(Specific_Road_Counts))

ggplot(Region_Counts, aes(x = Specific_Road_Counts, y = reorder(Region, Specific_Road_Counts), fill = Region)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = sprintf("%d (%.1f%%)", Specific_Road_Counts, Specific_Road_Counts_Percent)), 
            position = position_dodge(width = 1), hjust = -0.2, size = 3) +
  theme_minimal() +
  labs(title = "지역별 특화거리 현황", x = "특화거리 개수", y = "지역") +
   coord_cartesian(xlim = c(0, max(Region_Counts$Specific_Road_Counts) * 1.3)) + 
  theme(legend.position = "right", 
        plot.margin = margin(t = 1, r = 1, b = 1, l = 1, unit = "cm"),
        legend.box.margin = margin(10, 10, 10, 20),
        legend.text = element_text(size = 8),
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 8))

#(3)-6 Accommodation_Counts Visualization 

Region_Counts <- Region_Counts %>%
  mutate(Accommodation_Counts = replace_na(Accommodation_Counts, 0)) %>%
  mutate(Accommodation_Counts_Percent = Accommodation_Counts / sum(Accommodation_Counts) * 100) %>%
  arrange(desc(Accommodation_Counts))

ggplot(Region_Counts, aes(x = Accommodation_Counts, y = reorder(Region, Accommodation_Counts), fill = Region)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = sprintf("%d (%.1f%%)", Accommodation_Counts, Accommodation_Counts_Percent)), 
            position = position_dodge(width = 1), hjust = -0.2, size = 3) +
  theme_minimal() +
  labs(title = "지자체별 숙박업소 인허가 현황", x = "숙박업소 개수", y = "지역") +
   coord_cartesian(xlim = c(0, max(Region_Counts$Accommodation_Counts) * 1.3)) + 
  theme(legend.position = "right", 
        plot.margin = margin(t = 1, r = 1, b = 1, l = 1, unit = "cm"),
        legend.box.margin = margin(10, 10, 10, 20),
        legend.text = element_text(size = 8),
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 8))

#(3)-7 Waterpark_Counts Visualization 

Region_Counts <- Region_Counts %>%
  mutate(Waterpark_Counts = replace_na(Waterpark_Counts, 0)) %>%
  mutate(Waterpark_Counts_Percent = Waterpark_Counts / sum(Waterpark_Counts) * 100) %>%
  arrange(desc(Waterpark_Counts))

ggplot(Region_Counts, aes(x = Waterpark_Counts, y = reorder(Region, Waterpark_Counts), fill = Region)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = sprintf("%d (%.1f%%)", Waterpark_Counts, Waterpark_Counts_Percent)), 
            position = position_dodge(width = 1), hjust = -0.2, size = 3) +
  theme_minimal() +
  labs(title = "지역별 유원시설 현황", x = "유원시설 개수", y = "지역") +
   coord_cartesian(xlim = c(0, max(Region_Counts$Waterpark_Counts) * 1.3)) + 
  theme(legend.position = "right", 
        plot.margin = margin(t = 1, r = 1, b = 1, l = 1, unit = "cm"),
        legend.box.margin = margin(10, 10, 10, 20),
        legend.text = element_text(size = 8),
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 8))


#(3)-8 Museum_Counts Visualization 

Region_Counts <- Region_Counts %>%
  mutate(Museum_Counts = replace_na(Museum_Counts, 0)) %>%
  mutate(Museum_Counts_Percent = Museum_Counts / sum(Museum_Counts) * 100) %>%
  arrange(desc(Museum_Counts))

ggplot(Region_Counts, aes(x = Museum_Counts, y = reorder(Region, Museum_Counts), fill = Region)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = sprintf("%d (%.1f%%)", Museum_Counts, Museum_Counts_Percent)), 
            position = position_dodge(width = 1), hjust = -0.2, size = 3) +
  theme_minimal() +
  labs(title = "지역별 박물관, 미술관 현황", x = "박물관, 미술관 개수", y = "지역") +
   coord_cartesian(xlim = c(0, max(Region_Counts$Museum_Counts) * 1.3)) + 
  theme(legend.position = "right", 
        plot.margin = margin(t = 1, r = 1, b = 1, l = 1, unit = "cm"),
        legend.box.margin = margin(10, 10, 10, 20),
        legend.text = element_text(size = 8),
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 8))

#(3)-9 Recreational_forest_Counts Visualization 

Region_Counts <- Region_Counts %>%
  mutate(Recreational_forest_Counts = replace_na(Recreational_forest_Counts, 0)) %>%
  mutate(Recreational_forest_Counts_Percent = Recreational_forest_Counts / sum(Recreational_forest_Counts) * 100) %>%
  arrange(desc(Recreational_forest_Counts))

ggplot(Region_Counts, aes(x = Recreational_forest_Counts, y = reorder(Region, Recreational_forest_Counts), fill = Region)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = sprintf("%d (%.1f%%)", Recreational_forest_Counts, Recreational_forest_Counts_Percent)), 
            position = position_dodge(width = 1), hjust = -0.2, size = 3) +
  theme_minimal() +
  labs(title = "지역별 휴양림 현황", x = "휴양림 개수", y = "지역") +
   coord_cartesian(xlim = c(0, max(Region_Counts$Recreational_forest_Counts) * 1.3)) + 
  theme(legend.position = "right", 
        plot.margin = margin(t = 1, r = 1, b = 1, l = 1, unit = "cm"),
        legend.box.margin = margin(10, 10, 10, 20),
        legend.text = element_text(size = 8),
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 8))

#(3)-10 Performance_Counts Visualization 

Region_Counts <- Region_Counts %>%
  mutate(Performance_Counts = replace_na(Performance_Counts, 0)) %>%
  mutate(Performance_Counts_Percent = Performance_Counts / sum(Performance_Counts) * 100) %>%
  arrange(desc(Performance_Counts))

ggplot(Region_Counts, aes(x = Performance_Counts, y = reorder(Region, Performance_Counts), fill = Region)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = sprintf("%d (%.1f%%)", Performance_Counts, Performance_Counts_Percent)), 
            position = position_dodge(width = 1), hjust = -0.2, size = 3) +
  theme_minimal() +
  labs(title = "지역별 공연, 행사 현황", x = "공연, 행사 개수", y = "지역") +
   coord_cartesian(xlim = c(0, max(Region_Counts$Performance_Counts) * 1.3)) + 
  theme(legend.position = "right", 
        plot.margin = margin(t = 1, r = 1, b = 1, l = 1, unit = "cm"),
        legend.box.margin = margin(10, 10, 10, 20),
        legend.text = element_text(size = 8),
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 8))


```
```{r}
#(4) Analysing correlation and Visualization

#install.packages("reshape2")
library(reshape2)

exp_vis_search <- read_csv("exp+vis+search.csv", locale = locale(encoding = "EUC-KR"));exp_vis_search
Region_Counts


Region_merged_data <- merge(exp_vis_search, Region_Counts, by = "Region")

colnames(merged_data) <- c("Region", "Expenditure", "Visitors", "Search_Volume", "SouthKorea_Road_Counts", 
                           "Garosu_Gil_Counts", "Traditional_Heritage_Counts", "Cultural_Festival_Counts", 
                           "Specific_Road_Counts", "Accommodation_Counts", "Waterpark_Counts", 
                           "Museum_Counts", "Recreational_Forest_Counts", "Performance_Counts")


analysis_df <- merged_data[, c("Expenditure", "Visitors", "Search_Volume", "SouthKorea_Road_Counts", "Garosu_Gil_Counts", "Traditional_Heritage_Counts", "Cultural_Festival_Counts", "Specific_Road_Counts", "Accommodation_Counts", "Waterpark_Counts", "Museum_Counts", "Recreational_Forest_Counts", "Performance_Counts" )] ; analysis_df


correlation_matrix <- cor(analysis_df, use = "complete.obs", method = "pearson")
#print(correlation_matrix)

correlation_df <- melt(correlation_matrix)

highlight_vars <- c("Expenditure", "Visitors", "Search_Volume")
correlation_df$highlight <- ifelse(correlation_df$Var1 %in% highlight_vars & !(correlation_df$Var2 %in% highlight_vars) |
                                   correlation_df$Var2 %in% highlight_vars & !(correlation_df$Var1 %in% highlight_vars), 
                                   TRUE, FALSE)

corrplot(correlation_matrix, method = "number", tl.cex = 0.5, number.cex = 0.7) 


```
```{r}


# Install and load showtext package if not already installed
if (!require(showtext)) {
  install.packages("showtext")
  library(showtext)
}

# Add a Google font that supports Korean characters
font_add_google("Nanum Gothic", "nanumgothic")
showtext_auto()

# Example heatmap code (assuming 'correlation_df' is your correlation matrix dataframe)
library(ggplot2)

# Create heatmap plot with text annotations
ggplot(correlation_df, aes(Var2, Var1, fill = Freq)) +
  geom_tile(color = "white") +
  geom_text(aes(label = sprintf("%.2f", Freq)), size = 10) +  # Increased text size
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                       midpoint = 0, limit = c(-1, 1), space = "Lab", 
                       name = "Pearson\nCorrelation") +
  theme_minimal() + 
  theme(
    axis.text.x = element_text(angle = 45, vjust = 1, 
                               size = 15, hjust = 1, family = "nanumgothic"),
    axis.text.y = element_text(size = 15, family = "nanumgothic"),
    axis.title.x = element_text(size = 20, family = "nanumgothic"),  # Increased x-axis title size
    axis.title.y = element_text(size = 20, family = "nanumgothic"),  # Increased y-axis title size
    plot.title = element_text(size = 25, family = "nanumgothic", hjust = 0.5)  # Increased plot title size
  ) +
  coord_fixed() +
  labs(
    x = "Facilities and Events",  # Updated X-axis title
    y = "Visitor Data",  # Updated Y-axis title
    title = "Correlation Between Visitor Data and Facilities/Events"  # Plot title
  )


```




```{r}
#pie chart
# (1) Gyeonggido

Gyeonggido <- Region_merged_data  %>% filter(Region == "경기도") %>% select(SouthKorea_Road_Percent,Garosu_Gil_Percent,Traditional_heritage_Percent,Cultural_Festival_Percent,Specific_Road_Counts_Percent,Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

library(ggplot2)
library(dplyr)
library(tidyr)
library(ggtext)

# Assuming analysis_df is already loaded in your environment
Gyeonggido <- Region_merged_data  %>%
  filter(Region == "경기도") %>%
  select(SouthKorea_Road_Percent, Garosu_Gil_Percent, Traditional_heritage_Percent, Cultural_Festival_Percent, Specific_Road_Counts_Percent, Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

# Reshape the data for ggplot
Gyeonggido_long <- Gyeonggido %>%
  pivot_longer(cols = everything(), names_to = "Category", values_to = "Percent")

# Define new labels for the legend and x-axis
new_labels <- c(
  SouthKorea_Road_Percent = "길 관광",
  Garosu_Gil_Percent = "가로수길",
  Traditional_heritage_Percent = "향토문화유적",
  Cultural_Festival_Percent = "문화축제",
  Specific_Road_Counts_Percent = "전국지역특화거리",
  Accommodation_Counts_Percent = "숙박업소",
  Waterpark_Counts_Percent = "유원시설",
  Museum_Counts_Percent = "전국박물관/미술관",
  Recreational_forest_Counts_Percent = "휴양림",
  Performance_Counts_Percent = "공연행사"
)

# Map the new labels to the categories
Gyeonggido_long$Category <- factor(Gyeonggido_long$Category, levels = names(new_labels), labels = new_labels)

# Plotting with ggplot2
ggplot(Gyeonggido_long, aes(x = "", y = Percent, fill = Category)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +
  geom_text(aes(label = paste0(round(Percent, 1), "%")), position = position_stack(vjust = 0.5), size = 7) +
  scale_fill_manual(values = scales::hue_pal()(10), labels = new_labels) +
  theme_minimal() +
  labs(title = "Percent Distribution in 경기도") +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
   legend.text = element_text(size = 14),
  plot.title = element_text(size = 20, face = "bold")
  )
```
```{r}
# (2) Gangwondo

Gangwondo <- Region_merged_data  %>% filter(Region == "강원도") %>% select(SouthKorea_Road_Percent,Garosu_Gil_Percent,Traditional_heritage_Percent,Cultural_Festival_Percent,Specific_Road_Counts_Percent,Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

library(ggplot2)
library(dplyr)
library(tidyr)
library(ggtext)

# Assuming analysis_df is already loaded in your environment
Gangwondo <- Region_merged_data  %>%
  filter(Region == "강원도") %>%
  select(SouthKorea_Road_Percent, Garosu_Gil_Percent, Traditional_heritage_Percent, Cultural_Festival_Percent, Specific_Road_Counts_Percent, Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

# Reshape the data for ggplot
Gangwondo_long <- Gangwondo %>%
  pivot_longer(cols = everything(), names_to = "Category", values_to = "Percent")

# Define new labels for the legend and x-axis
new_labels <- c(
  SouthKorea_Road_Percent = "길 관광",
  Garosu_Gil_Percent = "가로수길",
  Traditional_heritage_Percent = "향토문화유적",
  Cultural_Festival_Percent = "문화축제",
  Specific_Road_Counts_Percent = "전국지역특화거리",
  Accommodation_Counts_Percent = "숙박업소",
  Waterpark_Counts_Percent = "유원시설",
  Museum_Counts_Percent = "전국박물관/미술관",
  Recreational_forest_Counts_Percent = "휴양림",
  Performance_Counts_Percent = "공연행사"
)

# Map the new labels to the categories
Gangwondo_long$Category <- factor(Gangwondo_long$Category, levels = names(new_labels), labels = new_labels)

# Plotting with ggplot2
ggplot(Gangwondo_long, aes(x = "", y = Percent, fill = Category)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +
  geom_text(aes(label = paste0(round(Percent, 1), "%")), position = position_stack(vjust = 0.5), size = 7) +
  scale_fill_manual(values = scales::hue_pal()(10), breaks = names(new_labels), labels = new_labels) +  # breaks와 labels를 직접 지정
  theme_minimal() +
  labs(title = "Percent Distribution in 강원도") +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.text = element_text(size = 14),
    plot.title = element_text(size = 20, face = "bold")
  )

```
```{r}
# (3) Gyeongnam

Gyeongnam <- Region_merged_data  %>% filter(Region == "경상남도") %>% select(SouthKorea_Road_Percent,Garosu_Gil_Percent,Traditional_heritage_Percent,Cultural_Festival_Percent,Specific_Road_Counts_Percent,Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

library(ggplot2)
library(dplyr)
library(tidyr)
library(ggtext)

# Assuming analysis_df is already loaded in your environment
Gyeongnam <- Region_merged_data  %>%
  filter(Region == "경상남도") %>%
  select(SouthKorea_Road_Percent, Garosu_Gil_Percent, Traditional_heritage_Percent, Cultural_Festival_Percent, Specific_Road_Counts_Percent, Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

# Reshape the data for ggplot
Gyeongnam_long <- Gyeongnam %>%
  pivot_longer(cols = everything(), names_to = "Category", values_to = "Percent")

# Define new labels for the legend and x-axis
new_labels <- c(
  SouthKorea_Road_Percent = "길 관광",
  Garosu_Gil_Percent = "가로수길",
  Traditional_heritage_Percent = "향토문화유적",
  Cultural_Festival_Percent = "문화축제",
  Specific_Road_Counts_Percent = "전국지역특화거리",
  Accommodation_Counts_Percent = "숙박업소",
  Waterpark_Counts_Percent = "유원시설",
  Museum_Counts_Percent = "전국박물관/미술관",
  Recreational_forest_Counts_Percent = "휴양림",
  Performance_Counts_Percent = "공연행사"
)

# Map the new labels to the categories
Gyeongnam_long$Category <- factor(Gyeongnam_long$Category, levels = names(new_labels), labels = new_labels)

# Plotting with ggplot2
ggplot(Gyeongnam_long, aes(x = "", y = Percent, fill = Category)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +
  geom_text(aes(label = paste0(round(Percent, 1), "%")), position = position_stack(vjust = 0.5), size = 5) +
  scale_fill_manual(values = scales::hue_pal()(10), labels = new_labels) +
  theme_minimal() +
  labs(title = "Percent Distribution in 경상남도") +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.text = element_text(size = 14),
    plot.title = element_text(size = 20, face = "bold")
  )
```
```{r}
# (4) Gyeongbuk

Gyeongbuk <- Region_merged_data  %>% filter(Region == "경상북도") %>% select(SouthKorea_Road_Percent,Garosu_Gil_Percent,Traditional_heritage_Percent,Cultural_Festival_Percent,Specific_Road_Counts_Percent,Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

library(ggplot2)
library(dplyr)
library(tidyr)
library(ggtext)

# Assuming analysis_df is already loaded in your environment
Gyeongbuk <- Region_merged_data  %>%
  filter(Region == "경상북도") %>%
  select(SouthKorea_Road_Percent, Garosu_Gil_Percent, Traditional_heritage_Percent, Cultural_Festival_Percent, Specific_Road_Counts_Percent, Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

# Reshape the data for ggplot
Gyeongbuk_long <- Gyeongbuk %>%
  pivot_longer(cols = everything(), names_to = "Category", values_to = "Percent")

# Define new labels for the legend and x-axis
new_labels <- c(
  SouthKorea_Road_Percent = "길 관광",
  Garosu_Gil_Percent = "가로수길",
  Traditional_heritage_Percent = "향토문화유적",
  Cultural_Festival_Percent = "문화축제",
  Specific_Road_Counts_Percent = "전국지역특화거리",
  Accommodation_Counts_Percent = "숙박업소",
  Waterpark_Counts_Percent = "유원시설",
  Museum_Counts_Percent = "전국박물관/미술관",
  Recreational_forest_Counts_Percent = "휴양림",
  Performance_Counts_Percent = "공연행사"
)

# Map the new labels to the categories
Gyeongbuk_long$Category <- factor(Gyeongbuk_long$Category, levels = names(new_labels), labels = new_labels)

# Plotting with ggplot2
ggplot(Gyeongbuk_long, aes(x = "", y = Percent, fill = Category)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +
  geom_text(aes(label = paste0(round(Percent, 1), "%")), position = position_stack(vjust = 0.5), size = 7) +
  scale_fill_manual(values = scales::hue_pal()(10), labels = new_labels) +
  theme_minimal() +
  labs(title = "Percent Distribution in 경상북도") +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.text = element_text(size = 14),
    plot.title = element_text(size = 20, face = "bold")
  )
```
```{r}
# (5) Gwangju

Gwangju <- Region_merged_data  %>% filter(Region == "광주광역시") %>% select(SouthKorea_Road_Percent,Garosu_Gil_Percent,Traditional_heritage_Percent,Cultural_Festival_Percent,Specific_Road_Counts_Percent,Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

library(ggplot2)
library(dplyr)
library(tidyr)
library(ggtext)

# Assuming analysis_df is already loaded in your environment
Gwangju <- Region_merged_data  %>%
  filter(Region == "광주광역시") %>%
  select(SouthKorea_Road_Percent, Garosu_Gil_Percent, Traditional_heritage_Percent, Cultural_Festival_Percent, Specific_Road_Counts_Percent, Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

# Reshape the data for ggplot
Gwangju_long <- Gwangju %>%
  pivot_longer(cols = everything(), names_to = "Category", values_to = "Percent")

# Define new labels for the legend and x-axis
new_labels <- c(
  SouthKorea_Road_Percent = "길 관광",
  Garosu_Gil_Percent = "가로수길",
  Traditional_heritage_Percent = "향토문화유적",
  Cultural_Festival_Percent = "문화축제",
  Specific_Road_Counts_Percent = "전국지역특화거리",
  Accommodation_Counts_Percent = "숙박업소",
  Waterpark_Counts_Percent = "유원시설",
  Museum_Counts_Percent = "전국박물관/미술관",
  Recreational_forest_Counts_Percent = "휴양림",
  Performance_Counts_Percent = "공연행사"
)

# Map the new labels to the categories
Gwangju_long$Category <- factor(Gwangju_long$Category, levels = names(new_labels), labels = new_labels)

# Plotting with ggplot2
ggplot(Gwangju_long[Gwangju_long$Percent >= 0.5, ], aes(x = "", y = Percent, fill = Category)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +
  geom_text(aes(label = ifelse(Percent != 0, paste0(round(Percent, 1), "%"), "")), position = position_stack(vjust = 0.5), size = 2) +
  scale_fill_manual(values = scales::hue_pal()(10), labels = new_labels) +
  theme_minimal() +
  labs(title = "Percent Distribution in 광주광역시") +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.text = element_text(size = 14),
    plot.title = element_text(size = 20, face = "bold")
  )

```
```{r}
# (6) Daegu

Daegu <- Region_merged_data  %>% filter(Region == "대구광역시") %>% select(SouthKorea_Road_Percent,Garosu_Gil_Percent,Traditional_heritage_Percent,Cultural_Festival_Percent,Specific_Road_Counts_Percent,Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

library(ggplot2)
library(dplyr)
library(tidyr)
library(ggtext)

# Assuming analysis_df is already loaded in your environment
Daegu <- Region_merged_data  %>%
  filter(Region == "대구광역시") %>%
  select(SouthKorea_Road_Percent, Garosu_Gil_Percent, Traditional_heritage_Percent, Cultural_Festival_Percent, Specific_Road_Counts_Percent, Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

# Reshape the data for ggplot
Daegu_long <- Daegu %>%
  pivot_longer(cols = everything(), names_to = "Category", values_to = "Percent")

# Define new labels for the legend and x-axis
new_labels <- c(
  SouthKorea_Road_Percent = "길 관광",
  Garosu_Gil_Percent = "가로수길",
  Traditional_heritage_Percent = "향토문화유적",
  Cultural_Festival_Percent = "문화축제",
  Specific_Road_Counts_Percent = "전국지역특화거리",
  Accommodation_Counts_Percent = "숙박업소",
  Waterpark_Counts_Percent = "유원시설",
  Museum_Counts_Percent = "전국박물관/미술관",
  Recreational_forest_Counts_Percent = "휴양림",
  Performance_Counts_Percent = "공연행사"
)

# Map the new labels to the categories
Daegu_long$Category <- factor(Daegu_long$Category, levels = names(new_labels), labels = new_labels)

# Plotting with ggplot2
ggplot(Daegu_long[Daegu_long$Percent >= 0.5, ], aes(x = "", y = Percent, fill = Category)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +
  geom_text(aes(label = paste0(round(Percent, 1), "%")), position = position_stack(vjust = 0.5), size = 5) +
  scale_fill_manual(values = scales::hue_pal()(10), labels = new_labels) +
  theme_minimal() +
  labs(title = "Percent Distribution in 대구광역시") +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.text = element_text(size = 14),
    plot.title = element_text(size = 20, face = "bold")
  )
```
```{r}
# (7) Daejeon

Daejeon <- Region_merged_data  %>% filter(Region == "대전광역시") %>% select(SouthKorea_Road_Percent,Garosu_Gil_Percent,Traditional_heritage_Percent,Cultural_Festival_Percent,Specific_Road_Counts_Percent,Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

library(ggplot2)
library(dplyr)
library(tidyr)
library(ggtext)

# Assuming analysis_df is already loaded in your environment
Daejeon <- Region_merged_data  %>%
  filter(Region == "대전광역시") %>%
  select(SouthKorea_Road_Percent, Garosu_Gil_Percent, Traditional_heritage_Percent, Cultural_Festival_Percent, Specific_Road_Counts_Percent, Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

# Reshape the data for ggplot
Daejeon_long <- Daejeon %>%
  pivot_longer(cols = everything(), names_to = "Category", values_to = "Percent")

# Define new labels for the legend and x-axis
new_labels <- c(
  SouthKorea_Road_Percent = "길 관광",
  Garosu_Gil_Percent = "가로수길",
  Traditional_heritage_Percent = "향토문화유적",
  Cultural_Festival_Percent = "문화축제",
  Specific_Road_Counts_Percent = "전국지역특화거리",
  Accommodation_Counts_Percent = "숙박업소",
  Waterpark_Counts_Percent = "유원시설",
  Museum_Counts_Percent = "전국박물관/미술관",
  Recreational_forest_Counts_Percent = "휴양림",
  Performance_Counts_Percent = "공연행사"
)

# Map the new labels to the categories
Daejeon_long$Category <- factor(Daejeon_long$Category, levels = names(new_labels), labels = new_labels)

# Plotting with ggplot2
ggplot(Daejeon_long[Daejeon_long$Percent >= 0.5, ], aes(x = "", y = Percent, fill = Category)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +
  geom_text(aes(label = paste0(round(Percent, 1), "%")), position = position_stack(vjust = 0.5), size = 3) +
  scale_fill_manual(values = scales::hue_pal()(10), labels = new_labels) +
  theme_minimal() +
  labs(title = "Percent Distribution in 대전광역시") +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.text = element_text(size = 14),
    plot.title = element_text(size = 20, face = "bold")
  )
```
```{r}
# (8) Busan

Busan <- Region_merged_data  %>% filter(Region == "부산광역시") %>% select(SouthKorea_Road_Percent,Garosu_Gil_Percent,Traditional_heritage_Percent,Cultural_Festival_Percent,Specific_Road_Counts_Percent,Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

library(ggplot2)
library(dplyr)
library(tidyr)
library(ggtext)

# Assuming analysis_df is already loaded in your environment
Busan <- Region_merged_data  %>%
  filter(Region == "부산광역시") %>%
  select(SouthKorea_Road_Percent, Garosu_Gil_Percent, Traditional_heritage_Percent, Cultural_Festival_Percent, Specific_Road_Counts_Percent, Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

# Reshape the data for ggplot
Busan_long <- Busan %>%
  pivot_longer(cols = everything(), names_to = "Category", values_to = "Percent")

# Define new labels for the legend and x-axis
new_labels <- c(
  SouthKorea_Road_Percent = "길 관광",
  Garosu_Gil_Percent = "가로수길",
  Traditional_heritage_Percent = "향토문화유적",
  Cultural_Festival_Percent = "문화축제",
  Specific_Road_Counts_Percent = "전국지역특화거리",
  Accommodation_Counts_Percent = "숙박업소",
  Waterpark_Counts_Percent = "유원시설",
  Museum_Counts_Percent = "전국박물관/미술관",
  Recreational_forest_Counts_Percent = "휴양림",
  Performance_Counts_Percent = "공연행사"
)

# Map the new labels to the categories
Busan_long$Category <- factor(Busan_long$Category, levels = names(new_labels), labels = new_labels)

# Plotting with ggplot2
ggplot(Busan_long[Busan_long$Percent >= 0.5, ], aes(x = "", y = Percent, fill = Category)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +
  geom_text(aes(label = paste0(round(Percent, 1), "%")), position = position_stack(vjust = 0.5), size = 5) +
  scale_fill_manual(values = scales::hue_pal()(10), labels = new_labels) +
  theme_minimal() +
  labs(title = "Percent Distribution in 부산광역시") +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.text = element_text(size = 14),
    plot.title = element_text(size = 20, face = "bold")
  )
```
```{r}
# (9) Seoul

Seoul <- Region_merged_data  %>% filter(Region == "서울특별시") %>% select(SouthKorea_Road_Percent,Garosu_Gil_Percent,Traditional_heritage_Percent,Cultural_Festival_Percent,Specific_Road_Counts_Percent,Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

library(ggplot2)
library(dplyr)
library(tidyr)
library(ggtext)

# Assuming analysis_df is already loaded in your environment
Seoul <- Region_merged_data  %>%
  filter(Region == "서울특별시") %>%
  select(SouthKorea_Road_Percent, Garosu_Gil_Percent, Traditional_heritage_Percent, Cultural_Festival_Percent, Specific_Road_Counts_Percent, Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

# Reshape the data for ggplot
Seoul_long <- Seoul %>%
  pivot_longer(cols = everything(), names_to = "Category", values_to = "Percent")

# Define new labels for the legend and x-axis
new_labels <- c(
  SouthKorea_Road_Percent = "길 관광",
  Garosu_Gil_Percent = "가로수길",
  Traditional_heritage_Percent = "향토문화유적",
  Cultural_Festival_Percent = "문화축제",
  Specific_Road_Counts_Percent = "전국지역특화거리",
  Accommodation_Counts_Percent = "숙박업소",
  Waterpark_Counts_Percent = "유원시설",
  Museum_Counts_Percent = "전국박물관/미술관",
  Recreational_forest_Counts_Percent = "휴양림",
  Performance_Counts_Percent = "공연행사"
)

# Map the new labels to the categories
Seoul_long$Category <- factor(Seoul_long$Category, levels = names(new_labels), labels = new_labels)

# Plotting with ggplot2
ggplot(Seoul_long[Seoul_long$Percent >= 0.5, ], aes(x = "", y = Percent, fill = Category)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +
  geom_text(aes(label = paste0(round(Percent, 1), "%")), position = position_stack(vjust = 0.5), size = 3) +
  scale_fill_manual(values = scales::hue_pal()(10), labels = new_labels) +
  theme_minimal() +
  labs(title = "Percent Distribution in 서울특별시") +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.text = element_text(size = 14),
    plot.title = element_text(size = 20, face = "bold")
  )
```
```{r}
# (10) Sejong

Sejong <- Region_merged_data  %>% filter(Region == "세종특별자치시") %>% select(SouthKorea_Road_Percent,Garosu_Gil_Percent,Traditional_heritage_Percent,Cultural_Festival_Percent,Specific_Road_Counts_Percent,Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

library(ggplot2)
library(dplyr)
library(tidyr)
library(ggtext)

# Assuming analysis_df is already loaded in your environment
Sejong <- Region_merged_data  %>%
  filter(Region == "세종특별자치시") %>%
  select(SouthKorea_Road_Percent, Garosu_Gil_Percent, Traditional_heritage_Percent, Cultural_Festival_Percent, Specific_Road_Counts_Percent, Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

# Reshape the data for ggplot
Sejong_long <- Sejong %>%
  pivot_longer(cols = everything(), names_to = "Category", values_to = "Percent")

# Define new labels for the legend and x-axis
new_labels <- c(
  SouthKorea_Road_Percent = "길 관광",
  Garosu_Gil_Percent = "가로수길",
  Traditional_heritage_Percent = "향토문화유적",
  Cultural_Festival_Percent = "문화축제",
  Specific_Road_Counts_Percent = "전국지역특화거리",
  Accommodation_Counts_Percent = "숙박업소",
  Waterpark_Counts_Percent = "유원시설",
  Museum_Counts_Percent = "전국박물관/미술관",
  Recreational_forest_Counts_Percent = "휴양림",
  Performance_Counts_Percent = "공연행사"
)

# Map the new labels to the categories
Sejong_long$Category <- factor(Sejong_long$Category, levels = names(new_labels), labels = new_labels)

# Plotting with ggplot2
ggplot(Sejong_long[Sejong_long$Percent >= 0.5, ], aes(x = "", y = Percent, fill = Category)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +
  geom_text(aes(label = paste0(round(Percent, 1), "%")), position = position_stack(vjust = 0.5), size = 5) +
  scale_fill_manual(values = scales::hue_pal()(10), labels = new_labels) +
  theme_minimal() +
  labs(title = "Percent Distribution in 세종특별자치시") +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.text = element_text(size = 14),
    plot.title = element_text(size = 20, face = "bold")
  )
```
```{r}
# (11) Ulsan

Ulsan <- Region_merged_data  %>% filter(Region == "울산광역시") %>% select(SouthKorea_Road_Percent,Garosu_Gil_Percent,Traditional_heritage_Percent,Cultural_Festival_Percent,Specific_Road_Counts_Percent,Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

library(ggplot2)
library(dplyr)
library(tidyr)
library(ggtext)

# Assuming analysis_df is already loaded in your environment
Ulsan <- Region_merged_data  %>%
  filter(Region == "울산광역시") %>%
  select(SouthKorea_Road_Percent, Garosu_Gil_Percent, Traditional_heritage_Percent, Cultural_Festival_Percent, Specific_Road_Counts_Percent, Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

# Reshape the data for ggplot
Ulsan_long <- Ulsan %>%
  pivot_longer(cols = everything(), names_to = "Category", values_to = "Percent")

# Define new labels for the legend and x-axis
new_labels <- c(
  SouthKorea_Road_Percent = "길 관광",
  Garosu_Gil_Percent = "가로수길",
  Traditional_heritage_Percent = "향토문화유적",
  Cultural_Festival_Percent = "문화축제",
  Specific_Road_Counts_Percent = "전국지역특화거리",
  Accommodation_Counts_Percent = "숙박업소",
  Waterpark_Counts_Percent = "유원시설",
  Museum_Counts_Percent = "전국박물관/미술관",
  Recreational_forest_Counts_Percent = "휴양림",
  Performance_Counts_Percent = "공연행사"
)

# Map the new labels to the categories
Ulsan_long$Category <- factor(Ulsan_long$Category, levels = names(new_labels), labels = new_labels)

# Plotting with ggplot2
ggplot(Ulsan_long, aes(x = "", y = Percent, fill = Category)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +
  geom_text(aes(label = paste0(round(Percent, 1), "%")), position = position_stack(vjust = 0.5), size = 4) +
  scale_fill_manual(values = scales::hue_pal()(10), labels = new_labels) +
  theme_minimal() +
  labs(title = "Percent Distribution in 울산광역시") +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.text = element_text(size = 14),
    plot.title = element_text(size = 20, face = "bold")
  )
```
```{r}
# (12) Incheon

Incheon <- Region_merged_data  %>% filter(Region == "인천광역시") %>% select(SouthKorea_Road_Percent,Garosu_Gil_Percent,Traditional_heritage_Percent,Cultural_Festival_Percent,Specific_Road_Counts_Percent,Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

library(ggplot2)
library(dplyr)
library(tidyr)
library(ggtext)

# Assuming analysis_df is already loaded in your environment
Incheon <- Region_merged_data  %>%
  filter(Region == "인천광역시") %>%
  select(SouthKorea_Road_Percent, Garosu_Gil_Percent, Traditional_heritage_Percent, Cultural_Festival_Percent, Specific_Road_Counts_Percent, Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

# Reshape the data for ggplot
Incheon_long <- Incheon %>%
  pivot_longer(cols = everything(), names_to = "Category", values_to = "Percent")

# Define new labels for the legend and x-axis
new_labels <- c(
  SouthKorea_Road_Percent = "길 관광",
  Garosu_Gil_Percent = "가로수길",
  Traditional_heritage_Percent = "향토문화유적",
  Cultural_Festival_Percent = "문화축제",
  Specific_Road_Counts_Percent = "전국지역특화거리",
  Accommodation_Counts_Percent = "숙박업소",
  Waterpark_Counts_Percent = "유원시설",
  Museum_Counts_Percent = "전국박물관/미술관",
  Recreational_forest_Counts_Percent = "휴양림",
  Performance_Counts_Percent = "공연행사"
)

# Map the new labels to the categories
Incheon_long$Category <- factor(Incheon_long$Category, levels = names(new_labels), labels = new_labels)

# Plotting with ggplot2
ggplot(Incheon_long, aes(x = "", y = Percent, fill = Category)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +
  geom_text(aes(label = paste0(round(Percent, 1), "%")), position = position_stack(vjust = 0.5), size = 7) +
  scale_fill_manual(values = scales::hue_pal()(10), labels = new_labels) +
  theme_minimal() +
  labs(title = "Percent Distribution in 인천광역시") +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.text = element_text(size = 14),
    plot.title = element_text(size = 20, face = "bold")
  )
```
```{r}
# (13) Jeonnam

Jeonnam <- Region_merged_data  %>% filter(Region == "전라남도") %>% select(SouthKorea_Road_Percent,Garosu_Gil_Percent,Traditional_heritage_Percent,Cultural_Festival_Percent,Specific_Road_Counts_Percent,Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

library(ggplot2)
library(dplyr)
library(tidyr)
library(ggtext)

# Assuming analysis_df is already loaded in your environment
Jeonnam <- Region_merged_data  %>%
  filter(Region == "전라남도") %>%
  select(SouthKorea_Road_Percent, Garosu_Gil_Percent, Traditional_heritage_Percent, Cultural_Festival_Percent, Specific_Road_Counts_Percent, Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

# Reshape the data for ggplot
Jeonnam_long <- Jeonnam %>%
  pivot_longer(cols = everything(), names_to = "Category", values_to = "Percent")

# Define new labels for the legend and x-axis
new_labels <- c(
  SouthKorea_Road_Percent = "길 관광",
  Garosu_Gil_Percent = "가로수길",
  Traditional_heritage_Percent = "향토문화유적",
  Cultural_Festival_Percent = "문화축제",
  Specific_Road_Counts_Percent = "전국지역특화거리",
  Accommodation_Counts_Percent = "숙박업소",
  Waterpark_Counts_Percent = "유원시설",
  Museum_Counts_Percent = "전국박물관/미술관",
  Recreational_forest_Counts_Percent = "휴양림",
  Performance_Counts_Percent = "공연행사"
)

# Map the new labels to the categories
Jeonnam_long$Category <- factor(Jeonnam_long$Category, levels = names(new_labels), labels = new_labels)

# Plotting with ggplot2
ggplot(Jeonnam_long, aes(x = "", y = Percent, fill = Category)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +
  geom_text(aes(label = paste0(round(Percent, 1), "%")), position = position_stack(vjust = 0.5), size = 5) +
  scale_fill_manual(values = scales::hue_pal()(10), labels = new_labels) +
  theme_minimal() +
  labs(title = "Percent Distribution in 전라남도") +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.text = element_text(size = 14),
    plot.title = element_text(size = 20, face = "bold")
  )
```
```{r}
# (14) Jeonbuk

Jeonbuk <- Region_merged_data  %>% filter(Region == "전라북도") %>% select(SouthKorea_Road_Percent,Garosu_Gil_Percent,Traditional_heritage_Percent,Cultural_Festival_Percent,Specific_Road_Counts_Percent,Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

library(ggplot2)
library(dplyr)
library(tidyr)
library(ggtext)

# Assuming analysis_df is already loaded in your environment
Jeonbuk <- Region_merged_data  %>%
  filter(Region == "전라북도") %>%
  select(SouthKorea_Road_Percent, Garosu_Gil_Percent, Traditional_heritage_Percent, Cultural_Festival_Percent, Specific_Road_Counts_Percent, Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

# Reshape the data for ggplot
Jeonbuk_long <- Jeonbuk %>%
  pivot_longer(cols = everything(), names_to = "Category", values_to = "Percent")

# Define new labels for the legend and x-axis
new_labels <- c(
  SouthKorea_Road_Percent = "길 관광",
  Garosu_Gil_Percent = "가로수길",
  Traditional_heritage_Percent = "향토문화유적",
  Cultural_Festival_Percent = "문화축제",
  Specific_Road_Counts_Percent = "전국지역특화거리",
  Accommodation_Counts_Percent = "숙박업소",
  Waterpark_Counts_Percent = "유원시설",
  Museum_Counts_Percent = "전국박물관/미술관",
  Recreational_forest_Counts_Percent = "휴양림",
  Performance_Counts_Percent = "공연행사"
)

# Map the new labels to the categories
Jeonbuk_long$Category <- factor(Jeonbuk_long$Category, levels = names(new_labels), labels = new_labels)

# Plotting with ggplot2
ggplot(Jeonbuk_long, aes(x = "", y = Percent, fill = Category)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +
  geom_text(aes(label = paste0(round(Percent, 1), "%")), position = position_stack(vjust = 0.5), size = 7) +
  scale_fill_manual(values = scales::hue_pal()(10), labels = new_labels) +
  theme_minimal() +
  labs(title = "Percent Distribution in 전라북도") +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.text = element_text(size = 14),
    plot.title = element_text(size = 20, face = "bold")
  )
```
```{r}
# (15) Jeju

Jeju <- Region_merged_data  %>% filter(Region == "제주특별자치도") %>% select(SouthKorea_Road_Percent,Garosu_Gil_Percent,Traditional_heritage_Percent,Cultural_Festival_Percent,Specific_Road_Counts_Percent,Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

library(ggplot2)
library(dplyr)
library(tidyr)
library(ggtext)

# Assuming analysis_df is already loaded in your environment
Jeju <- Region_merged_data  %>%
  filter(Region == "제주특별자치도") %>%
  select(SouthKorea_Road_Percent, Garosu_Gil_Percent, Traditional_heritage_Percent, Cultural_Festival_Percent, Specific_Road_Counts_Percent, Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

# Reshape the data for ggplot
Jeju_long <- Jeju %>%
  pivot_longer(cols = everything(), names_to = "Category", values_to = "Percent")

# Define new labels for the legend and x-axis
new_labels <- c(
  SouthKorea_Road_Percent = "길 관광",
  Garosu_Gil_Percent = "가로수길",
  Traditional_heritage_Percent = "향토문화유적",
  Cultural_Festival_Percent = "문화축제",
  Specific_Road_Counts_Percent = "전국지역특화거리",
  Accommodation_Counts_Percent = "숙박업소",
  Waterpark_Counts_Percent = "유원시설",
  Museum_Counts_Percent = "전국박물관/미술관",
  Recreational_forest_Counts_Percent = "휴양림",
  Performance_Counts_Percent = "공연행사"
)

# Map the new labels to the categories
Jeju_long$Category <- factor(Jeju_long$Category, levels = names(new_labels), labels = new_labels)

# Plotting with ggplot2
ggplot(Jeju_long, aes(x = "", y = Percent, fill = Category)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +
  geom_text(aes(label = paste0(round(Percent, 1), "%")), position = position_stack(vjust = 0.5), size = 5) +
  scale_fill_manual(values = scales::hue_pal()(10), labels = new_labels) +
  theme_minimal() +
  labs(title = "Percent Distribution in 제주특별자치도") +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.text = element_text(size = 14),
    plot.title = element_text(size = 20, face = "bold")
  )
```
```{r}
# (16) Chungnam

Chungnam <- Region_merged_data  %>% filter(Region == "충청남도") %>% select(SouthKorea_Road_Percent,Garosu_Gil_Percent,Traditional_heritage_Percent,Cultural_Festival_Percent,Specific_Road_Counts_Percent,Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

library(ggplot2)
library(dplyr)
library(tidyr)
library(ggtext)

# Assuming analysis_df is already loaded in your environment
Chungnam <- Region_merged_data  %>%
  filter(Region == "충청남도") %>%
  select(SouthKorea_Road_Percent, Garosu_Gil_Percent, Traditional_heritage_Percent, Cultural_Festival_Percent, Specific_Road_Counts_Percent, Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

# Reshape the data for ggplot
Chungnam_long <- Chungnam %>%
  pivot_longer(cols = everything(), names_to = "Category", values_to = "Percent")

# Define new labels for the legend and x-axis
new_labels <- c(
  SouthKorea_Road_Percent = "길 관광",
  Garosu_Gil_Percent = "가로수길",
  Traditional_heritage_Percent = "향토문화유적",
  Cultural_Festival_Percent = "문화축제",
  Specific_Road_Counts_Percent = "전국지역특화거리",
  Accommodation_Counts_Percent = "숙박업소",
  Waterpark_Counts_Percent = "유원시설",
  Museum_Counts_Percent = "전국박물관/미술관",
  Recreational_forest_Counts_Percent = "휴양림",
  Performance_Counts_Percent = "공연행사"
)

# Map the new labels to the categories
Chungnam_long$Category <- factor(Chungnam_long$Category, levels = names(new_labels), labels = new_labels)

# Plotting with ggplot2
ggplot(Chungnam_long, aes(x = "", y = Percent, fill = Category)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +
  geom_text(aes(label = paste0(round(Percent, 1), "%")), position = position_stack(vjust = 0.5), size = 5) +
  scale_fill_manual(values = scales::hue_pal()(10), labels = new_labels) +
  theme_minimal() +
  labs(title = "Percent Distribution in 충청남도") +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.text = element_text(size = 14),
    plot.title = element_text(size = 20, face = "bold")
  )
```
```{r}
# (17) Chungbuk

Chungbuk <- Region_merged_data  %>% filter(Region == "충청북도") %>% select(SouthKorea_Road_Percent,Garosu_Gil_Percent,Traditional_heritage_Percent,Cultural_Festival_Percent,Specific_Road_Counts_Percent,Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

library(ggplot2)
library(dplyr)
library(tidyr)
library(ggtext)

# Assuming analysis_df is already loaded in your environment
Chungbuk <- Region_merged_data  %>%
  filter(Region == "충청북도") %>%
  select(SouthKorea_Road_Percent, Garosu_Gil_Percent, Traditional_heritage_Percent, Cultural_Festival_Percent, Specific_Road_Counts_Percent, Accommodation_Counts_Percent, Waterpark_Counts_Percent, Museum_Counts_Percent, Recreational_forest_Counts_Percent, Performance_Counts_Percent)

# Reshape the data for ggplot
Chungbuk_long <- Chungbuk %>%
  pivot_longer(cols = everything(), names_to = "Category", values_to = "Percent")

# Define new labels for the legend and x-axis
new_labels <- c(
  SouthKorea_Road_Percent = "길 관광",
  Garosu_Gil_Percent = "가로수길",
  Traditional_heritage_Percent = "향토문화유적",
  Cultural_Festival_Percent = "문화축제",
  Specific_Road_Counts_Percent = "전국지역특화거리",
  Accommodation_Counts_Percent = "숙박업소",
  Waterpark_Counts_Percent = "유원시설",
  Museum_Counts_Percent = "전국박물관/미술관",
  Recreational_forest_Counts_Percent = "휴양림",
  Performance_Counts_Percent = "공연행사"
)

# Map the new labels to the categories
Chungbuk_long$Category <- factor(Chungbuk_long$Category, levels = names(new_labels), labels = new_labels)

# Plotting with ggplot2
ggplot(Chungbuk_long, aes(x = "", y = Percent, fill = Category)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +
  geom_text(aes(label = paste0(round(Percent, 1), "%")), position = position_stack(vjust = 0.5), size = 4) +
  scale_fill_manual(values = scales::hue_pal()(10), labels = new_labels) +
  theme_minimal() +
  labs(title = "Percent Distribution in 충청북도") +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.text = element_text(size = 14),
    plot.title = element_text(size = 20, face = "bold")
  )
```
```{r}

library(dplyr)
library(ggplot2)
library(tidyr)

# Assuming Region_merged_data is your data frame
# Step 1: Filter and select relevant columns
region_data <- Region_merged_data %>%
  filter(Region == "경기도") %>%
  select(SouthKorea_Road_Counts, Garosu_Gil_Counts, Traditional_heritage_Counts, Cultural_Festival_Counts,
         Specific_Road_Counts, Accommodation_Counts, Waterpark_Counts, Museum_Counts, Recreational_forest_Counts, Performance_Counts)

# Step 2: Summarize the data
category_sums <- region_data %>%
  summarise_all(~ sum(as.numeric(.), na.rm = TRUE)) %>%
  gather(key = "Category", value = "Count")

# Step 3: Calculate the total count
total_count <- sum(category_sums$Count)

# Step 4: Calculate the percentage
category_sums <- category_sums %>%
  mutate(Percentage = (Count / total_count) * 100)

# Step 5: Rename the categories for the plot
category_labels <- c("SouthKorea_Road_Counts" = "길 관광",
                     "Garosu_Gil_Counts" = "가로수길",
                     "Traditional_heritage_Counts" = "향토문화유적",
                     "Cultural_Festival_Counts" = "문화행사",
                     "Specific_Road_Counts" = "전국지역특화거리",
                     "Accommodation_Counts" = "숙박업소",
                     "Waterpark_Counts" = "유원시설",
                     "Museum_Counts" = "전국박물관/미술관",
                     "Recreational_forest_Counts" = "휴양림",
                     "Performance_Counts" = "공연")

category_sums <- category_sums %>%
  mutate(Category = recode(Category, !!!category_labels))

# Step 6: Create a bar plot with text labels
ggplot(category_sums, aes(x = Category, y = Percentage, fill = Category)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = sprintf("%.1f%%", Percentage)), vjust = -0.5, size = 3) +
  theme_minimal() +
  labs(title = "Percentage of Each Category Over the Total Count in 경기도",
       x = "Category",
       y = "Percentage (%)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(fill = guide_legend(title = "Category"))




```
```{r}
library(dplyr)


# Assuming Region_merged_data is your data frame
# Step 1: Filter and select relevant columns
region_data <- Region_merged_data %>%
  filter(Region == "경상남도") %>%
  select(SouthKorea_Road_Counts, Garosu_Gil_Counts, Traditional_heritage_Counts, Cultural_Festival_Counts,
         Specific_Road_Counts, Accommodation_Counts, Waterpark_Counts, Museum_Counts, Recreational_forest_Counts, Performance_Counts)

# Step 2: Summarize the data
category_sums <- region_data %>%
  summarise_all(~ sum(as.numeric(.), na.rm = TRUE)) %>%
  gather(key = "Category", value = "Count")

# Step 3: Calculate the total count
total_count <- sum(category_sums$Count)

# Step 4: Calculate the percentage
category_sums <- category_sums %>%
  mutate(Percentage = (Count / total_count) * 100)

# Step 5: Rename the categories for the plot
category_labels <- c("SouthKorea_Road_Counts" = "길 관광",
                     "Garosu_Gil_Counts" = "가로수길",
                     "Traditional_heritage_Counts" = "향토문화유적",
                     "Cultural_Festival_Counts" = "문화행사",
                     "Specific_Road_Counts" = "전국지역특화거리",
                     "Accommodation_Counts" = "숙박업소",
                     "Waterpark_Counts" = "유원시설",
                     "Museum_Counts" = "전국박물관/미술관",
                     "Recreational_forest_Counts" = "휴양림",
                     "Performance_Counts" = "공연")

category_sums <- category_sums %>%
  mutate(Category = recode(Category, !!!category_labels))


# Step 5: Create a bar plot
ggplot(category_sums, aes(x = Category, y = Percentage, fill = Category)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = sprintf("%.1f%%", Percentage)), vjust = -0.5, size = 3) +
  theme_minimal() +
  labs(title = "Percentage of Each Category Over the Total Count in 경상남도",
       x = "Category",
       y = "Percentage (%)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
library(dplyr)


# Assuming Region_merged_data is your data frame
# Step 1: Filter and select relevant columns
region_data <- Region_merged_data %>%
  filter(Region == "경상북도") %>%
  select(SouthKorea_Road_Counts, Garosu_Gil_Counts, Traditional_heritage_Counts, Cultural_Festival_Counts,
         Specific_Road_Counts, Accommodation_Counts, Waterpark_Counts, Museum_Counts, Recreational_forest_Counts, Performance_Counts)

# Step 2: Summarize the data
category_sums <- region_data %>%
  summarise_all(~ sum(as.numeric(.), na.rm = TRUE)) %>%
  gather(key = "Category", value = "Count")

# Step 3: Calculate the total count
total_count <- sum(category_sums$Count)

# Step 4: Calculate the percentage
category_sums <- category_sums %>%
  mutate(Percentage = (Count / total_count) * 100)

# Step 5: Rename the categories for the plot
category_labels <- c("SouthKorea_Road_Counts" = "길 관광",
                     "Garosu_Gil_Counts" = "가로수길",
                     "Traditional_heritage_Counts" = "향토문화유적",
                     "Cultural_Festival_Counts" = "문화행사",
                     "Specific_Road_Counts" = "전국지역특화거리",
                     "Accommodation_Counts" = "숙박업소",
                     "Waterpark_Counts" = "유원시설",
                     "Museum_Counts" = "전국박물관/미술관",
                     "Recreational_forest_Counts" = "휴양림",
                     "Performance_Counts" = "공연")

category_sums <- category_sums %>%
  mutate(Category = recode(Category, !!!category_labels))

# Step 5: Create a bar plot
ggplot(category_sums, aes(x = Category, y = Percentage, fill = Category)) +
   geom_text(aes(label = sprintf("%.1f%%", Percentage)), vjust = -0.5, size = 3) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Percentage of Each Category Over the Total Count in 경상북도",
       x = "Category",
       y = "Percentage (%)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
library(dplyr)


# Assuming Region_merged_data is your data frame
# Step 1: Filter and select relevant columns
region_data <- Region_merged_data %>%
  filter(Region == "광주광역시") %>%
  select(SouthKorea_Road_Counts, Garosu_Gil_Counts, Traditional_heritage_Counts, Cultural_Festival_Counts,
         Specific_Road_Counts, Accommodation_Counts, Waterpark_Counts, Museum_Counts, Recreational_forest_Counts, Performance_Counts)

# Step 2: Summarize the data
category_sums <- region_data %>%
  summarise_all(~ sum(as.numeric(.), na.rm = TRUE)) %>%
  gather(key = "Category", value = "Count")

# Step 3: Calculate the total count
total_count <- sum(category_sums$Count)

# Step 4: Calculate the percentage
category_sums <- category_sums %>%
  mutate(Percentage = (Count / total_count) * 100)

# Step 5: Rename the categories for the plot
category_labels <- c("SouthKorea_Road_Counts" = "길 관광",
                     "Garosu_Gil_Counts" = "가로수길",
                     "Traditional_heritage_Counts" = "향토문화유적",
                     "Cultural_Festival_Counts" = "문화행사",
                     "Specific_Road_Counts" = "전국지역특화거리",
                     "Accommodation_Counts" = "숙박업소",
                     "Waterpark_Counts" = "유원시설",
                     "Museum_Counts" = "전국박물관/미술관",
                     "Recreational_forest_Counts" = "휴양림",
                     "Performance_Counts" = "공연")

category_sums <- category_sums %>%
  mutate(Category = recode(Category, !!!category_labels))

# Step 5: Create a bar plot
ggplot(category_sums, aes(x = Category, y = Percentage, fill = Category)) +
   geom_text(aes(label = sprintf("%.1f%%", Percentage)), vjust = -0.5, size = 3) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Percentage of Each Category Over the Total Count in 광주광역시",
       x = "Category",
       y = "Percentage (%)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
library(dplyr)


# Assuming Region_merged_data is your data frame
# Step 1: Filter and select relevant columns
region_data <- Region_merged_data %>%
  filter(Region == "대구광역시") %>%
  select(SouthKorea_Road_Counts, Garosu_Gil_Counts, Traditional_heritage_Counts, Cultural_Festival_Counts,
         Specific_Road_Counts, Accommodation_Counts, Waterpark_Counts, Museum_Counts, Recreational_forest_Counts, Performance_Counts)

# Step 2: Summarize the data
category_sums <- region_data %>%
  summarise_all(~ sum(as.numeric(.), na.rm = TRUE)) %>%
  gather(key = "Category", value = "Count")

# Step 3: Calculate the total count
total_count <- sum(category_sums$Count)

# Step 4: Calculate the percentage
category_sums <- category_sums %>%
  mutate(Percentage = (Count / total_count) * 100)

# Step 5: Rename the categories for the plot
category_labels <- c("SouthKorea_Road_Counts" = "길 관광",
                     "Garosu_Gil_Counts" = "가로수길",
                     "Traditional_heritage_Counts" = "향토문화유적",
                     "Cultural_Festival_Counts" = "문화행사",
                     "Specific_Road_Counts" = "전국지역특화거리",
                     "Accommodation_Counts" = "숙박업소",
                     "Waterpark_Counts" = "유원시설",
                     "Museum_Counts" = "전국박물관/미술관",
                     "Recreational_forest_Counts" = "휴양림",
                     "Performance_Counts" = "공연")

category_sums <- category_sums %>%
  mutate(Category = recode(Category, !!!category_labels))


# Step 5: Create a bar plot
ggplot(category_sums, aes(x = Category, y = Percentage, fill = Category)) +
    geom_text(aes(label = sprintf("%.1f%%", Percentage)), vjust = -0.5, size = 3) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Percentage of Each Category Over the Total Count in 대구광역시",
       x = "Category",
       y = "Percentage (%)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
library(dplyr)


# Assuming Region_merged_data is your data frame
# Step 1: Filter and select relevant columns
region_data <- Region_merged_data %>%
  filter(Region == "대전광역시") %>%
  select(SouthKorea_Road_Counts, Garosu_Gil_Counts, Traditional_heritage_Counts, Cultural_Festival_Counts,
         Specific_Road_Counts, Accommodation_Counts, Waterpark_Counts, Museum_Counts, Recreational_forest_Counts, Performance_Counts)

# Step 2: Summarize the data
category_sums <- region_data %>%
  summarise_all(~ sum(as.numeric(.), na.rm = TRUE)) %>%
  gather(key = "Category", value = "Count")

# Step 3: Calculate the total count
total_count <- sum(category_sums$Count)

# Step 4: Calculate the percentage
category_sums <- category_sums %>%
  mutate(Percentage = (Count / total_count) * 100)

# Step 5: Rename the categories for the plot
category_labels <- c("SouthKorea_Road_Counts" = "길 관광",
                     "Garosu_Gil_Counts" = "가로수길",
                     "Traditional_heritage_Counts" = "향토문화유적",
                     "Cultural_Festival_Counts" = "문화행사",
                     "Specific_Road_Counts" = "전국지역특화거리",
                     "Accommodation_Counts" = "숙박업소",
                     "Waterpark_Counts" = "유원시설",
                     "Museum_Counts" = "전국박물관/미술관",
                     "Recreational_forest_Counts" = "휴양림",
                     "Performance_Counts" = "공연")

category_sums <- category_sums %>%
  mutate(Category = recode(Category, !!!category_labels))


# Step 5: Create a bar plot
ggplot(category_sums, aes(x = Category, y = Percentage, fill = Category)) +
    geom_text(aes(label = sprintf("%.1f%%", Percentage)), vjust = -0.5, size = 3) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Percentage of Each Category Over the Total Count in 대전광역시",
       x = "Category",
       y = "Percentage (%)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
library(dplyr)


# Assuming Region_merged_data is your data frame
# Step 1: Filter and select relevant columns
region_data <- Region_merged_data %>%
  filter(Region == "부산광역시") %>%
  select(SouthKorea_Road_Counts, Garosu_Gil_Counts, Traditional_heritage_Counts, Cultural_Festival_Counts,
         Specific_Road_Counts, Accommodation_Counts, Waterpark_Counts, Museum_Counts, Recreational_forest_Counts, Performance_Counts)

# Step 2: Summarize the data
category_sums <- region_data %>%
  summarise_all(~ sum(as.numeric(.), na.rm = TRUE)) %>%
  gather(key = "Category", value = "Count")

# Step 3: Calculate the total count
total_count <- sum(category_sums$Count)

# Step 4: Calculate the percentage
category_sums <- category_sums %>%
  mutate(Percentage = (Count / total_count) * 100)

# Step 5: Rename the categories for the plot
category_labels <- c("SouthKorea_Road_Counts" = "길 관광",
                     "Garosu_Gil_Counts" = "가로수길",
                     "Traditional_heritage_Counts" = "향토문화유적",
                     "Cultural_Festival_Counts" = "문화행사",
                     "Specific_Road_Counts" = "전국지역특화거리",
                     "Accommodation_Counts" = "숙박업소",
                     "Waterpark_Counts" = "유원시설",
                     "Museum_Counts" = "전국박물관/미술관",
                     "Recreational_forest_Counts" = "휴양림",
                     "Performance_Counts" = "공연")

category_sums <- category_sums %>%
  mutate(Category = recode(Category, !!!category_labels))


# Step 5: Create a bar plot
ggplot(category_sums, aes(x = Category, y = Percentage, fill = Category)) +
    geom_text(aes(label = sprintf("%.1f%%", Percentage)), vjust = -0.5, size = 3) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Percentage of Each Category Over the Total Count in 부산광역시",
       x = "Category",
       y = "Percentage (%)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
library(dplyr)


# Assuming Region_merged_data is your data frame
# Step 1: Filter and select relevant columns
region_data <- Region_merged_data %>%
  filter(Region == "서울특별시") %>%
  select(SouthKorea_Road_Counts, Garosu_Gil_Counts, Traditional_heritage_Counts, Cultural_Festival_Counts,
         Specific_Road_Counts, Accommodation_Counts, Waterpark_Counts, Museum_Counts, Recreational_forest_Counts, Performance_Counts)

# Step 2: Summarize the data
category_sums <- region_data %>%
  summarise_all(~ sum(as.numeric(.), na.rm = TRUE)) %>%
  gather(key = "Category", value = "Count")

# Step 3: Calculate the total count
total_count <- sum(category_sums$Count)

# Step 4: Calculate the percentage
category_sums <- category_sums %>%
  mutate(Percentage = (Count / total_count) * 100)

# Step 5: Rename the categories for the plot
category_labels <- c("SouthKorea_Road_Counts" = "길 관광",
                     "Garosu_Gil_Counts" = "가로수길",
                     "Traditional_heritage_Counts" = "향토문화유적",
                     "Cultural_Festival_Counts" = "문화행사",
                     "Specific_Road_Counts" = "전국지역특화거리",
                     "Accommodation_Counts" = "숙박업소",
                     "Waterpark_Counts" = "유원시설",
                     "Museum_Counts" = "전국박물관/미술관",
                     "Recreational_forest_Counts" = "휴양림",
                     "Performance_Counts" = "공연")

category_sums <- category_sums %>%
  mutate(Category = recode(Category, !!!category_labels))


# Step 5: Create a bar plot
ggplot(category_sums, aes(x = Category, y = Percentage, fill = Category)) +
    geom_text(aes(label = sprintf("%.1f%%", Percentage)), vjust = -0.5, size = 3) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Percentage of Each Category Over the Total Count in 서울특별시",
       x = "Category",
       y = "Percentage (%)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
library(dplyr)


# Assuming Region_merged_data is your data frame
# Step 1: Filter and select relevant columns
region_data <- Region_merged_data %>%
  filter(Region == "세종특별자치시") %>%
  select(SouthKorea_Road_Counts, Garosu_Gil_Counts, Traditional_heritage_Counts, Cultural_Festival_Counts,
         Specific_Road_Counts, Accommodation_Counts, Waterpark_Counts, Museum_Counts, Recreational_forest_Counts, Performance_Counts)

# Step 2: Summarize the data
category_sums <- region_data %>%
  summarise_all(~ sum(as.numeric(.), na.rm = TRUE)) %>%
  gather(key = "Category", value = "Count")

# Step 3: Calculate the total count
total_count <- sum(category_sums$Count)

# Step 4: Calculate the percentage
category_sums <- category_sums %>%
  mutate(Percentage = (Count / total_count) * 100)

# Step 5: Rename the categories for the plot
category_labels <- c("SouthKorea_Road_Counts" = "길 관광",
                     "Garosu_Gil_Counts" = "가로수길",
                     "Traditional_heritage_Counts" = "향토문화유적",
                     "Cultural_Festival_Counts" = "문화행사",
                     "Specific_Road_Counts" = "전국지역특화거리",
                     "Accommodation_Counts" = "숙박업소",
                     "Waterpark_Counts" = "유원시설",
                     "Museum_Counts" = "전국박물관/미술관",
                     "Recreational_forest_Counts" = "휴양림",
                     "Performance_Counts" = "공연")

category_sums <- category_sums %>%
  mutate(Category = recode(Category, !!!category_labels))


# Step 5: Create a bar plot
ggplot(category_sums, aes(x = Category, y = Percentage, fill = Category)) +
    geom_text(aes(label = sprintf("%.1f%%", Percentage)), vjust = -0.5, size = 3) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Percentage of Each Category Over the Total Count in 세종특별자치시",
       x = "Category",
       y = "Percentage (%)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
library(dplyr)


# Assuming Region_merged_data is your data frame
# Step 1: Filter and select relevant columns
region_data <- Region_merged_data %>%
  filter(Region == "울산광역시") %>%
  select(SouthKorea_Road_Counts, Garosu_Gil_Counts, Traditional_heritage_Counts, Cultural_Festival_Counts,
         Specific_Road_Counts, Accommodation_Counts, Waterpark_Counts, Museum_Counts, Recreational_forest_Counts, Performance_Counts)

# Step 2: Summarize the data
category_sums <- region_data %>%
  summarise_all(~ sum(as.numeric(.), na.rm = TRUE)) %>%
  gather(key = "Category", value = "Count")

# Step 3: Calculate the total count
total_count <- sum(category_sums$Count)

# Step 4: Calculate the percentage
category_sums <- category_sums %>%
  mutate(Percentage = (Count / total_count) * 100)

# Step 5: Rename the categories for the plot
category_labels <- c("SouthKorea_Road_Counts" = "길 관광",
                     "Garosu_Gil_Counts" = "가로수길",
                     "Traditional_heritage_Counts" = "향토문화유적",
                     "Cultural_Festival_Counts" = "문화행사",
                     "Specific_Road_Counts" = "전국지역특화거리",
                     "Accommodation_Counts" = "숙박업소",
                     "Waterpark_Counts" = "유원시설",
                     "Museum_Counts" = "전국박물관/미술관",
                     "Recreational_forest_Counts" = "휴양림",
                     "Performance_Counts" = "공연")

category_sums <- category_sums %>%
  mutate(Category = recode(Category, !!!category_labels))


# Step 5: Create a bar plot
ggplot(category_sums, aes(x = Category, y = Percentage, fill = Category)) +
    geom_text(aes(label = sprintf("%.1f%%", Percentage)), vjust = -0.5, size = 3) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Percentage of Each Category Over the Total Count in 울산광역시",
       x = "Category",
       y = "Percentage (%)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
library(dplyr)


# Assuming Region_merged_data is your data frame
# Step 1: Filter and select relevant columns
region_data <- Region_merged_data %>%
  filter(Region == "인천광역시") %>%
  select(SouthKorea_Road_Counts, Garosu_Gil_Counts, Traditional_heritage_Counts, Cultural_Festival_Counts,
         Specific_Road_Counts, Accommodation_Counts, Waterpark_Counts, Museum_Counts, Recreational_forest_Counts, Performance_Counts)

# Step 2: Summarize the data
category_sums <- region_data %>%
  summarise_all(~ sum(as.numeric(.), na.rm = TRUE)) %>%
  gather(key = "Category", value = "Count")

# Step 3: Calculate the total count
total_count <- sum(category_sums$Count)

# Step 4: Calculate the percentage
category_sums <- category_sums %>%
  mutate(Percentage = (Count / total_count) * 100)

# Step 5: Rename the categories for the plot
category_labels <- c("SouthKorea_Road_Counts" = "길 관광",
                     "Garosu_Gil_Counts" = "가로수길",
                     "Traditional_heritage_Counts" = "향토문화유적",
                     "Cultural_Festival_Counts" = "문화행사",
                     "Specific_Road_Counts" = "전국지역특화거리",
                     "Accommodation_Counts" = "숙박업소",
                     "Waterpark_Counts" = "유원시설",
                     "Museum_Counts" = "전국박물관/미술관",
                     "Recreational_forest_Counts" = "휴양림",
                     "Performance_Counts" = "공연")

category_sums <- category_sums %>%
  mutate(Category = recode(Category, !!!category_labels))


# Step 5: Create a bar plot
ggplot(category_sums, aes(x = Category, y = Percentage, fill = Category)) +
    geom_text(aes(label = sprintf("%.1f%%", Percentage)), vjust = -0.5, size = 3) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Percentage of Each Category Over the Total Count in 인천광역시",
       x = "Category",
       y = "Percentage (%)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
library(dplyr)


# Assuming Region_merged_data is your data frame
# Step 1: Filter and select relevant columns
region_data <- Region_merged_data %>%
  filter(Region == "전라남도") %>%
  select(SouthKorea_Road_Counts, Garosu_Gil_Counts, Traditional_heritage_Counts, Cultural_Festival_Counts,
         Specific_Road_Counts, Accommodation_Counts, Waterpark_Counts, Museum_Counts, Recreational_forest_Counts, Performance_Counts)

# Step 2: Summarize the data
category_sums <- region_data %>%
  summarise_all(~ sum(as.numeric(.), na.rm = TRUE)) %>%
  gather(key = "Category", value = "Count")

# Step 3: Calculate the total count
total_count <- sum(category_sums$Count)

# Step 4: Calculate the percentage
category_sums <- category_sums %>%
  mutate(Percentage = (Count / total_count) * 100)

# Step 5: Rename the categories for the plot
category_labels <- c("SouthKorea_Road_Counts" = "길 관광",
                     "Garosu_Gil_Counts" = "가로수길",
                     "Traditional_heritage_Counts" = "향토문화유적",
                     "Cultural_Festival_Counts" = "문화행사",
                     "Specific_Road_Counts" = "전국지역특화거리",
                     "Accommodation_Counts" = "숙박업소",
                     "Waterpark_Counts" = "유원시설",
                     "Museum_Counts" = "전국박물관/미술관",
                     "Recreational_forest_Counts" = "휴양림",
                     "Performance_Counts" = "공연")

category_sums <- category_sums %>%
  mutate(Category = recode(Category, !!!category_labels))

# Step 5: Create a bar plot
ggplot(category_sums, aes(x = Category, y = Percentage, fill = Category)) +
    geom_text(aes(label = sprintf("%.1f%%", Percentage)), vjust = -0.5, size = 3) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Percentage of Each Category Over the Total Count in 전라남도",
       x = "Category",
       y = "Percentage (%)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```
```{r}
library(dplyr)


# Assuming Region_merged_data is your data frame
# Step 1: Filter and select relevant columns
region_data <- Region_Counts %>%
  filter(Region == "전라북도") %>%
  select(SouthKorea_Road_Counts, Garosu_Gil_Counts, Traditional_heritage_Counts, Cultural_Festival_Counts,
         Specific_Road_Counts, Accommodation_Counts, Waterpark_Counts, Museum_Counts, Recreational_forest_Counts, Performance_Counts)

# Step 2: Summarize the data
category_sums <- region_data %>%
  summarise_all(~ sum(as.numeric(.), na.rm = TRUE)) %>%
  gather(key = "Category", value = "Count")

# Step 3: Calculate the total count
total_count <- sum(category_sums$Count)

# Step 4: Calculate the percentage
category_sums <- category_sums %>%
  mutate(Percentage = (Count / total_count) * 100)

# Step 5: Rename the categories for the plot
category_labels <- c("SouthKorea_Road_Counts" = "길 관광",
                     "Garosu_Gil_Counts" = "가로수길",
                     "Traditional_heritage_Counts" = "향토문화유적",
                     "Cultural_Festival_Counts" = "문화행사",
                     "Specific_Road_Counts" = "전국지역특화거리",
                     "Accommodation_Counts" = "숙박업소",
                     "Waterpark_Counts" = "유원시설",
                     "Museum_Counts" = "전국박물관/미술관",
                     "Recreational_forest_Counts" = "휴양림",
                     "Performance_Counts" = "공연")

category_sums <- category_sums %>%
  mutate(Category = recode(Category, !!!category_labels))

# Step 5: Create a bar plot
ggplot(category_sums, aes(x = Category, y = Percentage, fill = Category)) +
    geom_text(aes(label = sprintf("%.1f%%", Percentage)), vjust = -0.5, size = 3) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Percentage of Each Category Over the Total Count in 전라북도",
       x = "Category",
       y = "Percentage (%)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r}
library(dplyr)


# Assuming Region_merged_data is your data frame
# Step 1: Filter and select relevant columns
region_data <- Region_Counts %>%
  filter(Region == "강원도") %>%
  select(SouthKorea_Road_Counts, Garosu_Gil_Counts, Traditional_heritage_Counts, Cultural_Festival_Counts,
         Specific_Road_Counts, Accommodation_Counts, Waterpark_Counts, Museum_Counts, Recreational_forest_Counts, Performance_Counts)

# Step 2: Summarize the data
category_sums <- region_data %>%
  summarise_all(~ sum(as.numeric(.), na.rm = TRUE)) %>%
  gather(key = "Category", value = "Count")

# Step 3: Calculate the total count
total_count <- sum(category_sums$Count)

# Step 4: Calculate the percentage
category_sums <- category_sums %>%
  mutate(Percentage = (Count / total_count) * 100)

# Step 5: Rename the categories for the plot
category_labels <- c("SouthKorea_Road_Counts" = "길 관광",
                     "Garosu_Gil_Counts" = "가로수길",
                     "Traditional_heritage_Counts" = "향토문화유적",
                     "Cultural_Festival_Counts" = "문화행사",
                     "Specific_Road_Counts" = "전국지역특화거리",
                     "Accommodation_Counts" = "숙박업소",
                     "Waterpark_Counts" = "유원시설",
                     "Museum_Counts" = "전국박물관/미술관",
                     "Recreational_forest_Counts" = "휴양림",
                     "Performance_Counts" = "공연")

category_sums <- category_sums %>%
  mutate(Category = recode(Category, !!!category_labels))

# Step 5: Create a bar plot
ggplot(category_sums, aes(x = Category, y = Percentage, fill = Category)) +
    geom_text(aes(label = sprintf("%.1f%%", Percentage)), vjust = -0.5, size = 3) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Percentage of Each Category Over the Total Count in 강원도",
       x = "Category",
       y = "Percentage (%)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
library(dplyr)


# Assuming Region_merged_data is your data frame
# Step 1: Filter and select relevant columns
region_data <- Region_merged_data %>%
  filter(Region == "제주특별자치도") %>%
  select(SouthKorea_Road_Counts, Garosu_Gil_Counts, Traditional_heritage_Counts, Cultural_Festival_Counts,
         Specific_Road_Counts, Accommodation_Counts, Waterpark_Counts, Museum_Counts, Recreational_forest_Counts, Performance_Counts)

# Step 2: Summarize the data
category_sums <- region_data %>%
  summarise_all(~ sum(as.numeric(.), na.rm = TRUE)) %>%
  gather(key = "Category", value = "Count")

# Step 3: Calculate the total count
total_count <- sum(category_sums$Count)

# Step 4: Calculate the percentage
category_sums <- category_sums %>%
  mutate(Percentage = (Count / total_count) * 100)

# Step 5: Rename the categories for the plot
category_labels <- c("SouthKorea_Road_Counts" = "길 관광",
                     "Garosu_Gil_Counts" = "가로수길",
                     "Traditional_heritage_Counts" = "향토문화유적",
                     "Cultural_Festival_Counts" = "문화행사",
                     "Specific_Road_Counts" = "전국지역특화거리",
                     "Accommodation_Counts" = "숙박업소",
                     "Waterpark_Counts" = "유원시설",
                     "Museum_Counts" = "전국박물관/미술관",
                     "Recreational_forest_Counts" = "휴양림",
                     "Performance_Counts" = "공연")

category_sums <- category_sums %>%
  mutate(Category = recode(Category, !!!category_labels))


# Step 5: Create a bar plot
ggplot(category_sums, aes(x = Category, y = Percentage, fill = Category)) +
    geom_text(aes(label = sprintf("%.1f%%", Percentage)), vjust = -0.5, size = 3) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Percentage of Each Category Over the Total Count in 제주특별자치도",
       x = "Category",
       y = "Percentage (%)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
library(dplyr)


# Assuming Region_merged_data is your data frame
# Step 1: Filter and select relevant columns
region_data <- Region_merged_data %>%
  filter(Region == "충청남도") %>%
  select(SouthKorea_Road_Counts, Garosu_Gil_Counts, Traditional_heritage_Counts, Cultural_Festival_Counts,
         Specific_Road_Counts, Accommodation_Counts, Waterpark_Counts, Museum_Counts, Recreational_forest_Counts, Performance_Counts)

# Step 2: Summarize the data
category_sums <- region_data %>%
  summarise_all(~ sum(as.numeric(.), na.rm = TRUE)) %>%
  gather(key = "Category", value = "Count")

# Step 3: Calculate the total count
total_count <- sum(category_sums$Count)

# Step 4: Calculate the percentage
category_sums <- category_sums %>%
  mutate(Percentage = (Count / total_count) * 100)

# Step 5: Rename the categories for the plot
category_labels <- c("SouthKorea_Road_Counts" = "길 관광",
                     "Garosu_Gil_Counts" = "가로수길",
                     "Traditional_heritage_Counts" = "향토문화유적",
                     "Cultural_Festival_Counts" = "문화행사",
                     "Specific_Road_Counts" = "전국지역특화거리",
                     "Accommodation_Counts" = "숙박업소",
                     "Waterpark_Counts" = "유원시설",
                     "Museum_Counts" = "전국박물관/미술관",
                     "Recreational_forest_Counts" = "휴양림",
                     "Performance_Counts" = "공연")

category_sums <- category_sums %>%
  mutate(Category = recode(Category, !!!category_labels))


# Step 5: Create a bar plot
ggplot(category_sums, aes(x = Category, y = Percentage, fill = Category)) +
    geom_text(aes(label = sprintf("%.1f%%", Percentage)), vjust = -0.5, size = 3) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Percentage of Each Category Over the Total Count in 충청남도",
       x = "Category",
       y = "Percentage (%)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
library(dplyr)


# Assuming Region_merged_data is your data frame
# Step 1: Filter and select relevant columns
region_data <- Region_merged_data %>%
  filter(Region == "충청북도") %>%
  select(SouthKorea_Road_Counts, Garosu_Gil_Counts, Traditional_heritage_Counts, Cultural_Festival_Counts,
         Specific_Road_Counts, Accommodation_Counts, Waterpark_Counts, Museum_Counts, Recreational_forest_Counts, Performance_Counts)

# Step 2: Summarize the data
category_sums <- region_data %>%
  summarise_all(~ sum(as.numeric(.), na.rm = TRUE)) %>%
  gather(key = "Category", value = "Count")

# Step 3: Calculate the total count
total_count <- sum(category_sums$Count)

# Step 4: Calculate the percentage
category_sums <- category_sums %>%
  mutate(Percentage = (Count / total_count) * 100)

# Step 5: Rename the categories for the plot
category_labels <- c("SouthKorea_Road_Counts" = "길 관광",
                     "Garosu_Gil_Counts" = "가로수길",
                     "Traditional_heritage_Counts" = "향토문화유적",
                     "Cultural_Festival_Counts" = "문화행사",
                     "Specific_Road_Counts" = "전국지역특화거리",
                     "Accommodation_Counts" = "숙박업소",
                     "Waterpark_Counts" = "유원시설",
                     "Museum_Counts" = "전국박물관/미술관",
                     "Recreational_forest_Counts" = "휴양림",
                     "Performance_Counts" = "공연")

category_sums <- category_sums %>%
  mutate(Category = recode(Category, !!!category_labels))


# Step 5: Create a bar plot
ggplot(category_sums, aes(x = Category, y = Percentage, fill = Category)) +
    geom_text(aes(label = sprintf("%.1f%%", Percentage)), vjust = -0.5, size = 3) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Percentage of Each Category Over the Total Count in 충청북도",
       x = "Category",
       y = "Percentage (%)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

